docs/en/index.rst
No openvino doc in readthedocs .
Add  openvino.md to index.rst
No
=> [Doc]: add openvino.md to index.rst

.github/workflows/build.yml
To add the coverage report.
added uploading report to `.github/workflows/build.yml`
No
=> [Enhancement] support coverage

README.md, README_zh-CN.md
1. Add MMDeploy short introduction
2. Add acknowledgement to OpenPPL team
`README.md` and `README_zh-CN.md`
=> [Docs] update acknowledgement and MMDeploy's short introduction

docs/en/benchmark.md, docs/zh_cn/benchmark.md
Fix the missed performance results of the pplnn for mmseg.
=> [Docs] fix pplnn performance results for mmseg

.pre-commit-config.yaml
Unified pre-commit tools to GH server.
Update the flake8 to GH in pre-commit
=> Update flake8 to GitHub in pre-commit

README.md, README_zh-CN.md, docs/en/codebases/mmcls.md, docs/en/codebases/mmdet.md, docs/en/codebases/mmedit.md, docs/en/codebases/mmocr.md, docs/en/codebases/mmseg.md, docs/zh_cn/conf.py
Fix Readme docs link.
Fix codebase docs model config.
=> 【Docs】fix docs

mmdeploy/backend/onnxruntime/wrapper.py, tools/test.py
device cannot sucessfully control through argments "device"
If this PR introduces a new feature, it is better to …
=> modified device selection

csrc/preprocess/cuda/resize_impl.cpp
=> Fixed build using latest ppl.cv master

mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py, tests/test_codebase/test_mmdet/test_mmdet_core.py, tests/test_codebase/test_mmdet/test_mmdet_models.py, tests/test_ops/test_ops.py
#37 
Do not recover the tensors after padding in NMS.
WIP. We will test all the detection models.
=> [Fix] Avoid outputing empty tensor in NMS

mmdeploy/utils/export_info.py
For SDK python API usage. #27 
Modified `mmdeploy/utils/export_info.py`
No
=> [Enhancement] dump cls_name

mmdeploy/codebase/base/mmcodebase.py, mmdeploy/codebase/mmcls/deploy/mmclassification.py
#14 
1. Add comment for `__build_codebase_class`.
2. Catch up on the `@staticmethod` for `MMClassification::build_dataloader`
=> [Fix] Fix details of MMCodebase

docs/en/build.md, docs/zh_cn/build.md
issue #69 
en/build.md, zh_cn/build.md
=> correct path of pplcv_DIR

docs/en/build.md, docs/zh_cn/build.md
issue #70 
en/build.md, zh_cn/build.md
2. The modification is covered by …
=> Correct pip install

docs/en/benchmark.md, docs/en/codebases/mmseg.md, docs/en/supported_models.md, docs/zh_cn/benchmark.md, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmseg/deploy/segmentation_model.py
Test and verify the conversion and deployment of UNet in mmdet
None
=> Support UNet in mmseg

tools/check_env.py
Fix check_env.py script to check codebase version.
Fix check_env.py
python tools/check_env.py
=> [Fix]fix check_env

mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py, mmdeploy/codebase/mmdet/deploy/utils.py
Optimize delta2bbox according to latest mmdetection.
remove expand, less nodes generated.
old:
new:
=> [Enhancement] optimize delta2bboxes

mmdeploy/pytorch/functions/interpolate.py, tests/test_ops/test_ops.py
Fix a type error when computing scale_factor in rewriting interpolate.
=> [Fix]use float in scale factor

README.md, README_zh-CN.md
Group OpenMMLab projects based on their taxonomy, so that users could see related projects together. Refer to https://github.com/open-mmlab/mmcv/pull/1744 and https://github.com/open-mmlab/mmdetection/pull/7239
README documents
If this PR introduces a new feature, it …
=> [enhancement] Reorganizing OpenMMLab projects in readme

mmdeploy/version.py
=> bump version

.github/workflows/build.yml, mmdeploy/codebase/mmpose/deploy/pose_detection.py, requirements/optional.txt
- Fix https://github.com/open-mmlab/mmdeploy/issues/218
- Update CI since https://github.com/open-mmlab/mmdeploy/issues/165 is fixed in mmpose==v0.24.0
- Change create_input for mmpose>=v0.24.0
- Update CI
None
=> fix mmpose

docs/en/codebases/mmpose.md
=> fix typo in mmpose.md

mmdeploy/apis/calibration.py, mmdeploy/apis/extract_model.py, mmdeploy/apis/inference.py, mmdeploy/apis/pytorch2onnx.py, mmdeploy/apis/visualize.py, mmdeploy/backend/ncnn/onnx2ncnn.py, mmdeploy/backend/openvino/onnx2openvino.py, mmdeploy/backend/tensorrt/onnx2tensorrt.py
Add example in mmdeploy/apis.
mmdeploy/apis/*
=> [Dostring]add example in apis docstring

docker/CPU/Dockerfile, docker/GPU/Dockerfile, docs/en/tutorials/how_to_use_docker.md, docs/zh_cn/tutorials/how_to_use_docker.md
… or [IP: 91.189.88.142 80] in Dockerfile
If this PR introduces a new feature, it is better to list some use cases …
=> Fix docker build for users inside

csrc/archive/CMakeLists.txt
`archive` and `json` weren't installed correctly
csrc/archive/CMakeLists.txt
=> fix the installation of archive and json

.gitignore, csrc/backend_ops/tensorrt/batched_nms/allClassNMS.cu, csrc/backend_ops/tensorrt/batched_nms/kernel.cu, csrc/backend_ops/tensorrt/batched_nms/kernel.h, docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md
Add a FAQ to `How to install mmdeploy on Jetsons`
=> [Docs] add faq to `How to install mmdeploy on Jetsons`

mmdeploy/apis/visualize.py, tools/deploy.py
MMDeploy is failed on headless devices.(#238 )
we check $DISPLAY for headless devices. If headless device, we don't show the visualization.
None.
On headless device, execute tools/deploy.py as [get_started](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md)
3. If the modification has a dependency on …
=> [Fix] add support for headless device

docs/zh_cn/build/windows.md
In the cell where OpenCV is presented, the cell's format is not correct
1. move </td> at the end of the cell
1. Pre-commit or other linting tools are used to …
=> table format is wrong

docs/en/faq.md
=> update faq about WinError 1455

csrc/core/utils/formatter.h
=> [Fix] include missing <type_traits> for formatter.h

mmdeploy/backend/ncnn/wrapper.py, mmdeploy/codebase/base/backend_model.py
When we test mmpose litehrnet performance, on linux cpu it will be too slow. So we want to use ncnn vulkan on linux.
As ncnn vulkan is a backend property, so we changed the ncnn_wrapper.py and backend_models.py to pass the `use_gpu` parameter.
None.
You should set the `use_gpu` key on the ncnn backend config.
3. If the …
=> [Enhancement] Support ncnn vulkan

.circleci/config.yml
[MMDeploy's CircleCI project](https://app.circleci.com/pipelines/github/open-mmlab/mmdeploy) has been established.
And it's necessary to check in the config file '.circleci/config.yml' to master. Otherwise, PR cannot pass the CircleCI test.
Add a new file .circleci/config.yml, in which only a linting job is added.
I will make another PR to add more jobs and workflows.
If so, please describe how it breaks the …
=> init circleci

docs/en/index.rst
Review redundant doc tree.
update readthedoc index.rst
no BC-breaking.
no need test.
4. The documentation has been modified accordingly, like docstring or example …
=> fix(docs): remove redundant doc tree

docker/CPU/Dockerfile
address #356 
docker/CPU/Dockerfile
=> fix cpu dockerfile

docs/zh_cn/tutorials/chapter_03_pytorch2onnx.md
Upload tutorial 03.
Since #234 has not been merges, the notebook files are not involved in the tutorial.
=> Tutorial 03: torch2onnx

csrc/apis/python/pose_detector.cpp
pose-detedtor -> pose-detector
=> [Typo] typo-fix

csrc/net/ort/ort_net.cpp, csrc/net/trt/trt_net.cpp
ONNXTensorElementDataType case ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL return DataType::kINT8
nvinfer1::DataType case nvinfer1::DataType::kBOOL return DataType::kINT8
=> ort_net ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL and Tensorrt nvinfer1::DataType::kBOOL 

CMakeLists.txt, csrc/core/utils/source_location.h
resolves #413
fix incorrect use of feature test macros that causes compilation fail on recent compilers.
1. Pre-commit or other linting tools are used to fix …
=> [Fix] fix feature test for `std::source_location`

csrc/core/model.cpp
fix format string that triggers compilation errors when std::source_location is available for latest compilers.
resolves #414
If this PR introduces a new feature, it is better …
=> [Fix] fix format string

csrc/apis/c/pose_detector.cpp, csrc/apis/python/pose_detector.cpp, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
1. mmpose python api:
a) the boxes parameter should be n x m x 4 // (n_image x m_box x coordinate)
b) the boxes parameter can be empty
2. fix c api (no process if bbox_count is 0)
=> fix mmpose api

mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py, mmdeploy/codebase/mmdet3d/models/pillar_encode.py
Fix pillar_encode rewrite func. The original function has redundant calculation, and I modified the function to make the function calculation smaller.
None.
=> [Fix]fix pillarencode

.github/workflows/build.yml, requirements/optional.txt
The same fix as dev-0.5.0 branch.
Add Nvidia apt-key.
Limit requirements of MMPose. …
=> [Fix] Fix ci in master branch

docs/en/conf.py, docs/zh_cn/conf.py, requirements/readthedocs.txt
Fix API documentation.
- Before the PR
- After the PR
- docs/en/conf.py
- docs/zh_cn/conf.py
1. Pre-commit or other linting tools are used to fix the potential …
=> [Docs] Fix API documentation

tests/test_utils/test_util.py
`tests/test_utils/test_util.py` failed on windows.
Create new file with `open`, and move `target()` outside the function.
=> [Fix] Fix windows unit test

tools/deploy.py
Fix display bugs for windows, refer to #330 
We check the platform and the environment at the same time.
None.
None.
4. The documentation has been modified accordingly, …
=> [Fix] Fix display bugs for windows

.github/scripts/doc_link_checker.py, .github/workflows/check-doc-link.yml, README_zh-CN.md, docs/zh_cn/03-benchmark/benchmark.md
fix zh_CN REAME link error.
improve `doc_link_checker.py` test coverage, support single file.
1. Pre-commit or other linting tools are used to fix the potential …
=> fix(zh_CN): doc link

tools/deploy.py
`--work-dir` is an optional arg of deploy.py while missing the default value.
=> [Fix] set optional arg a default value

csrc/backend_ops/tensorrt/common_impl/trt_cuda_helper.cu, csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv.cpp, csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cu, csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cuh
https://github.com/open-mmlab/mmdeploy/issues/464
Support DCN TensorRT fp16 mode. …
=> [Enhancement] Support DeformConv TensorRT fp16

docs/en/benchmark.md, docs/en/codebases/mmdet.md, docs/zh_cn/03-benchmark/benchmark.md, docs/zh_cn/03-benchmark/supported_models.md, mmdeploy/codebase/mmdet/models/dense_heads/__init__.py, mmdeploy/codebase/mmdet/models/dense_heads/reppoints_head.py, tests/test_codebase/test_mmdet/test_mmdet_models.py
https://github.com/open-mmlab/mmdeploy/issues/439
Add reppoints TensorRT support. …
=> [Feature] Support reppoints TensorRT

mmdeploy/apis/calibration.py, mmdeploy/apis/inference.py, mmdeploy/apis/pytorch2onnx.py, mmdeploy/apis/visualize.py, mmdeploy/backend/tensorrt/onnx2tensorrt.py
Describe the feature
As shown in the following picture, there are unpleasant blanks in the strings.
We need to remove them.
There are unpleasant blanks in the strings in doc common，we need to remove them.
So I fix doc common and remove '\' which is used for switching a new line.
Files change
`mmdeploy/apis/calibration.py ` , 
`mmdeploy/apis/inference.py` , 
`mmdeploy/apis/pytorch2onnx.py` , 
`mmdeploy/apis/visualize.py` , 
`mmdeploy/backend/tensorrt/onnx2tensorrt.py`
Does the modification introduce changes that break the …
=> Fix docstring format

csrc/backend_ops/common/modulated_deform_conv/modulated_deform_conv_cuda.cuh, csrc/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv.cpp, csrc/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu, csrc/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv_kernel.hpp
This PR adds TensorRT fp16 support for modulated deformable Conv.
Add mdcn fp16. …
=> [Enhancement] Add TensorRT fp16 support for MDCN

docs/zh_cn/tutorials/chapter_05_onnx_model_editing.md
=> Tutorial 05: ONNX Model Editing

mmdeploy/backend/pplnn/__init__.py
=> [Fix] Fix tools/checkenv.py

mmdeploy/codebase/mmseg/models/decode_heads/psp_head.py
Fix asserttation failure for PSPNet with torchscript [dynamic shape](https://github.com/open-mmlab/mmdeploy/blob/6fa1787a04dac4ab75690de7b569b33d81d1cce1/mmdeploy/utils/config_utils.py#L198) config 
None
=> fix pspnet torchscript conversion

tests/regression/mmrotate.yml, tools/regression_test.py
Add regression test config for mmrotate. Rotated Retinanet only. …
=> [RegressionTest] Add mmrotate regression test

docs/zh_cn/01-how-to-build/windows.md, docs/zh_cn/04-developer-guide/do_regression_test.md, mmdeploy/apis/__init__.py
Fix typo
* Update do_regression_test doc
* Add import fail description
2. The …
=> docs(do_regression_test): fix-typo

configs/mmocr/text-detection/text-detection_tensorrt-fp16_dynamic-320x320-2240x2240.py, configs/mmocr/text-detection/text-detection_tensorrt-int8_dynamic-320x320-2240x2240.py, configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py, docs/zh_cn/04-developer-guide/do_regression_test.md, tests/regression/mmocr.yml
change mmocr input resolution and update regression tests.
=> change resolution and fix regression test for mmocr

docs/zh_cn/04-developer-guide/do_regression_test.md, tests/regression/mmdet.yml, tools/regression_test.py
Fix test ncnn failure in regression test
Fix test ncnn failure in regression test
None
=> Fix test ncnn failure in regression test

csrc/apis/c/pose_detector.cpp, csrc/codebase/mmpose/topdown_affine.cpp, csrc/codebase/mmpose/topdown_get_bbox_center_scale.cpp, mmdeploy/codebase/mmpose/deploy/pose_detection.py
=> compat mmpose v0.26 (sdk)

csrc/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.cpp, mmdeploy/apis/onnx/export.py
Peephole optimizer failed.
Fix bug of peephole optimizer, set optmize=False as default. …
=> [Fix] disable onnx export optimizer for 0.5.0

csrc/apis/c/classifier.h, csrc/apis/c/detector.h, csrc/apis/c/executor.h, csrc/apis/c/pipeline.h, csrc/apis/c/pose_detector.h, csrc/apis/c/restorer.h, csrc/apis/c/rotated_detector.h, csrc/apis/c/segmentor.h, csrc/apis/c/text_detector.h, csrc/apis/c/text_recognizer.h
=> document async APIs as experimental

.github/workflows/build.yml, mmdeploy/apis/tensorrt/__init__.py, requirements/optional.txt
=> fix build ci not triggerred

demo/csrc/image_classification.cpp
mmdeploy_classifier_release_result accepts wrong res address.
=> fix mmcls-c-demo

docs/en/01-how-to-build/jetsons.md
fix a typo described in issue #585
=> fix a typo in Build for Jetson

csrc/mmdeploy/net/ncnn/ncnn_net.cpp
OCR TextDet DBNet model converter got wrong shape of ncnn, which is because of the ncnn_net implementation error.
Fix 3-dim output shape.
None.
None.
4. The documentation …
=> [Fix ]fix ncnn textdet

mmdeploy/codebase/mmcls/models/backbones/shufflenet_v2.py, mmdeploy/codebase/mmcls/models/backbones/vision_transformer.py
Users with low version mmcls might get error.
Move import int rewriter.
2. The …
=> [Fix] Reduce mmcls version dependency

docs/zh_cn/01-how-to-build/linux-x86_64.md
中文文档部分
same with https://github.com/open-mmlab/mmdeploy/pull/654
=> [Document] ' -> "

csrc/mmdeploy/execution/expand.h
Simplify `mmdeploy::Expand`.
None.
=> simplify `mmdeploy::Expand` sender adaptor

mmdeploy/codebase/mmdet/models/backbones.py, mmdeploy/utils/test.py, tests/test_codebase/test_mmdet/test_mmdet_models.py
1. Fix bugs in ncnn unit test.
2. Replace 8 Slice in Focus module with a Transpose. …
=> [Enhancement] Fix ncnn unittest

.circleci/config.yml, .circleci/docker/Dockerfile, .circleci/scripts/linux/build.sh, .circleci/scripts/linux/convert_onnxruntime.sh, .circleci/scripts/linux/install_onnxruntime.sh, .circleci/scripts/linux/install_python.sh, .circleci/scripts/windows/install_onnxruntime.ps1, .circleci/scripts/windows/install_opencv.ps1, .circleci/test.yml, requirements/codebases.txt, tests/test_csrc/capi/test_classifier.cpp, tests/test_csrc/capi/test_detector.cpp, tests/test_csrc/capi/test_model.cpp, tests/test_csrc/capi/test_restorer.cpp, tests/test_csrc/capi/test_segmentor.cpp, tests/test_csrc/capi/test_text_detector.cpp, tests/test_csrc/capi/test_text_recognizer.cpp, tests/test_csrc/model/test_directory_model.cpp, tests/test_csrc/model/test_zip_model.cpp, tests/test_csrc/net/test_ncnn_net.cpp, tests/test_csrc/net/test_openvino_net.cpp, tests/test_csrc/net/test_ort_net.cpp, tests/test_csrc/net/test_ppl_net.cpp, tests/test_csrc/net/test_trt_net.cpp, tests/test_csrc/preprocess/test_default_format_bundle.cpp, tests/test_csrc/preprocess/test_load.cpp, tests/test_csrc/test_resource.h
Add more tests in circleci
2. The modification is covered by complete unit …
=> update the circleci config file by adding workflows both for linux, windows and linux-gpu

csrc/mmdeploy/codebase/mmocr/contour_expand.cpp, csrc/mmdeploy/codebase/mmocr/cpu/dbnet.cpp, csrc/mmdeploy/codebase/mmocr/cuda/dbnet.cpp, csrc/mmdeploy/codebase/mmocr/panet.cpp, csrc/mmdeploy/codebase/mmocr/pixel_group.cpp, csrc/mmdeploy/codebase/mmocr/psenet.cpp, csrc/mmdeploy/codebase/mmocr/warp.cpp, csrc/mmdeploy/codebase/mmpose/keypoints_from_heatmap.cpp, csrc/mmdeploy/codebase/mmpose/keypoints_from_regression.cpp, csrc/mmdeploy/codebase/mmrotate/oriented_object_detection.cpp, csrc/mmdeploy/core/utils/filesystem.h, csrc/mmdeploy/execution/schedulers/schedulers.cpp, csrc/mmdeploy/utils/opencv/opencv_utils.cpp, csrc/mmdeploy/utils/opencv/opencv_utils.h, tests/test_csrc/preprocess/test_compose.cpp, tests/test_csrc/preprocess/test_crop.cpp, tests/test_csrc/preprocess/test_default_format_bundle.cpp, tests/test_csrc/preprocess/test_image2tensor.cpp, tests/test_csrc/preprocess/test_load.cpp, tests/test_csrc/preprocess/test_normalize.cpp, tests/test_csrc/preprocess/test_pad.cpp, tests/test_csrc/preprocess/test_resize.cpp
Fix build on clang-14 and NDK-24
=> [Fix] fix clang build

tests/test_codebase/test_mmdet/test_mmdet_models.py
SSD NCNN unittest failed with seg fault, because dynamic shape uses explicit input_names, which ncnn `find_blob_index_by_name` failed.
explicitly write correct input names.
None.
None. …
=> [Fix] fix ssd ncnn ut

mmdeploy/apis/pytorch2onnx.py
=> fix passing img_metas to pytorch2onnx for mmedit

mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
=> [Bug] fix c4 for torchscript

mmdeploy/pytorch/ops/pad.py
Add version control to padding rewriting.
=> add version control

mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py, tests/regression/mmdet.yml
Fix cascade mask rcnn onnx shape bugs mentioned in #768 
cascade roi head
None.
```bash
python deploy.py ../configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py ../../../../data_example/mmdet/configs/cascade_rcnn/cascade_mask_rcnn_r50_fpn_1x_coco.py ../../../../data_example/mmdet/checkpoints/cascade_mask_rcnn_r50_fpn_1x_coco_20200203-9d4dcb24.pth ../../../../data_example/mmdet/coco0724_800x1344.jpg --work-dir ./
```
2. The …
=> [Fix] fix cascade mask rcnn

csrc/mmdeploy/apis/python/classifier.cpp, csrc/mmdeploy/apis/python/detector.cpp, csrc/mmdeploy/apis/python/pose_detector.cpp, csrc/mmdeploy/apis/python/restorer.cpp, csrc/mmdeploy/apis/python/rotated_detector.cpp, csrc/mmdeploy/apis/python/segmentor.cpp, csrc/mmdeploy/apis/python/text_detector.cpp, csrc/mmdeploy/apis/python/text_recognizer.cpp, demo/python/image_classification.py, demo/python/image_restorer.py, demo/python/image_segmentation.py, demo/python/object_detection.py, demo/python/ocr.py, demo/python/pose_detection.py, demo/python/rotated_object_detection.py
1. The current SDK Python bindings doesn't support kwargs
2. Support single image inference directly
Take `object_detection.py` as an example, 
- pass keyword args when initializing `Detector`
```python
detector = Detector(
model_path=args.model_path, device_name=args.device_name, device_id=0)
```
- make callable `__call__` accept single image
```python
bboxes, labels, masks = detector(img)
```
If so, please …
=> [Enhancement] support kwargs in SDK python bindings

setup.py
Support setup on the environment without PyTorch.
Add EXT_TYPE
2. The …
=> [Fix] Support setup on environment without PyTorch

csrc/mmdeploy/net/ppl/ppl_net.cpp
This feature is ready in pplnn-0.8.1. I forgot to turn it on in #564.
=> [Fix][pplnn] Import algorithm from buffer

csrc/mmdeploy/apis/python/pose_detector.cpp
The length of py:list should equal to the number of imgs. 
#794 #844
=> [FIX] fix mmpose python api

mmdeploy/backend/sdk/export_info.py, tests/test_utils/test_util.py, tools/deploy.py
=> [Fix] fix device error in dump-info

docs/en/02-how-to-run/convert_model.md, docs/zh_cn/02-how-to-run/convert_model.md
deploy.py 的参数讲清楚一点。for https://github.com/open-mmlab/mmdeploy/issues/524 
更新文档
=> docs(convert_model): update description

tests/test_codebase/test_mmdet/test_mmdet_models.py
Here is a ut failed but skipped in CI.
Fix ut.
None.
None.
=> [Fix] fix ut failed

mmdeploy/pytorch/functions/tensor_setitem.py, tests/test_codebase/test_mmocr/test_mmocr_models.py, tests/test_pytorch/test_pytorch_functions.py
Fix setitem for `x[:stop] = 1` where `x.dim()>1`
Fix some ut in `tests/test_mmocr`
1. Pre-commit …
=> [Fix] Fix setitem and UT in mmocr

tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/build_ubuntu_x64_ort.py, tools/scripts/build_ubuntu_x64_pplnn.py, tools/scripts/build_ubuntu_x64_torchscript.py
update script install
add `git submodule update`
=> CI(tools/scripts): add submodule init and update

mmdeploy/mmcv/ops/nms_rotated.py
fix https://github.com/open-mmlab/mmdeploy/issues/975
Fix nms_rotated
None
=> fix mmrotate

mmdeploy/backend/sdk/wrapper.py, mmdeploy/utils/__init__.py, mmdeploy/utils/device.py, tests/regression/mmcls.yml, tests/test_utils/test_util.py, tools/regression_test.py
fix regression test failed when 
1. metafile not exists
2. running `test.py` with sdk + ort(cuda device).
3. running `test.py` with sdk + trt(device=cuda:0)
None
4. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
5. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
6. The documentation has been modified accordingly, like docstring or example …
=> fix regression test 

.github/workflows/backend-ort.yml
=> fix(CI): typo

mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py
Missing sqrt could lead to wrong inference result after converted to backend models for PAA.
Add missing sqrt for PAA's score calculaiton.
None.
3. If the modification has a dependency on downstream projects of a newer …
=> [Fix] Add missing sqrt for PAA's score calculaiton

docs/en/01-how-to-build/linux-x86_64.md, docs/zh_cn/01-how-to-build/linux-x86_64.md, mmdeploy/backend/tensorrt/utils.py
fix model convert crash for cu102+trt8+mmdet3d centerpoint
* Update doc to install cu102 patch
* Disable cublaslt heuristic for cu102 …
=> fix(backend): disable cublaslt for cu102

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
=> fix mmdet showresult

mmdeploy/codebase/mmdet/models/roi_heads/test_mixins.py
=> [Bug] fix two stage batch dynamic

docs/en/05-supported-backends/onnxruntime.md, docs/en/05-supported-backends/tensorrt.md, docs/en/05-supported-backends/torchscript.md, docs/zh_cn/05-supported-backends/onnxruntime.md, docs/zh_cn/05-supported-backends/tensorrt.md, docs/zh_cn/05-supported-backends/torchscript.md
=> [Fix] Fix docs under supported-backends fold

mmdeploy/apis/visualize.py, tools/deploy.py
* Headless device should not disable real inference
* Every model conversion must execute backend inference
Headless device would run backend inference.
4. The …
=> improvement(visualize.py): headless enable inference

docs/en/03-benchmark/quantization.md, docs/zh_cn/03-benchmark/quantization.md
Detail results: https://github.com/Qingrenn/mmdeploy-summer-camp/blob/main/week4/result.md
Add Hourglass pose detection quantization evaluation result.
Detail results: https://github.com/Qingrenn/mmdeploy-summer-camp/blob/main/week4/result.md
Add Hourglass pose detection quantization evaluation result.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code …
=> [Docs] Add Hourglass pose detection quantization evaluation result.

tools/profile.py
Replace mmcv by mmengine
If this PR introduces a new feature, it is better to list some use cases here, and update …
=> Replace mmcv by mmengine

configs/mmcls/classification_sdk_dynamic.py, configs/mmdet/detection/detection_sdk_dynamic.py, configs/mmdet/instance-seg/instance-seg_sdk_dynamic.py, mmdeploy/codebase/base/task.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmcls/deploy/classification_model.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmocr/deploy/text_detection.py, mmdeploy/codebase/mmocr/deploy/text_recognition.py
Please note that the results of the SDK classification demo will be different from mmcls as ResizeEdge is replaced to Resize.
=> [2.0] Support SDK for det and cls

mmdeploy/pytorch/functions/__init__.py, mmdeploy/pytorch/functions/mod.py, tests/test_pytorch/test_pytorch_functions.py
Torch (1.11+) will generate Mod ONNX operator which is not supported by TRT.
=> [Feature] add mod rewriter for TRT

configs/text-detection_ncnn-int8_static.py, docs/en/03-benchmark/quantization.md, docs/zh_cn/03-benchmark/quantization.md
Add the result of quantization of model TextSnake from MMOCR
Add the result of quantization of model TextSnake from MMOCR
Result from https://github.com/BrokenArrow1404/2022-MMLAB-SUMMERCAMP/blob/main/week4/README.md
Add deploy config for quantization of TextSnake 
Does the modification introduce changes that break the backward-compatibility of the downstream …
=> Add result of quantization of TextSnake

mmdeploy/pytorch/ops/layer_norm.py, tests/test_pytorch/test_pytorch_ops.py
https://github.com/open-mmlab/mmdeploy/issues/1011
https://github.com/pytorch/pytorch/issues/84563 for more detail.
Add a new symbolic rewriter for layer norm. …
=> Fix layer norm

mmdeploy/apis/pytorch2torchscript.py, mmdeploy/apis/torch_jit/trace.py, mmdeploy/codebase/mmocr/models/text_detection/single_stage_text_detector.py
Torchscript backend failed on all codebases except mmocr after merge #1006 
Only ocr use img_metas
None.
None.
4. The documentation has been modified accordingly, like …
=> [Fix] fix torchscript

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
In mmdet 2.0, it is called pad_param instead of border
object_detection_model.py
None.
mmyolo should change it respectively. …
=> [Fix] border -> pad_param

docs/en/01-how-to-build/jetsons.md, docs/zh_cn/01-how-to-build/jetsons.md
=> docs(jetsons.md): fix desc

tools/scripts/ubuntu_utils.py
Fix ubuntu20 script add useless ppa.
Add libopencv-dev version check, if >=3, do not add ppa.
4. The documentation has been modified accordingly, like docstring or …
=> improvement(ubuntu_utils.py): check upstream libopencv-dev version

.circleci/docker/Dockerfile, .circleci/test.yml, csrc/mmdeploy/codebase/mmocr/short_scale_aspect_jitter.cpp
=> Dev 1.x cpp11

docs/en/02-how-to-run/quantize_model.md, docs/zh_cn/02-how-to-run/quantize_model.md
PPQ has updated and fixed many bugs.
Update doc about ppq.
2. The modification …
=> docs(quantization.md): remove ppq commit

README.md, README_zh-CN.md
reformat supported backends table
readme both in English and Chinese 
2. The …
=> reformat supported backends table in readme

mmdeploy/codebase/mmedit/deploy/super_resolution.py
SDK of mmedit failed.
Fix mmedit 2.0 preprocess function
None.
None.
=> [Fix] Fix mmedit 2.0 dump info

csrc/mmdeploy/apis/python/CMakeLists.txt
build error happened when try to make precompiled package
remove `execution.cpp` from csrc/api/python/CMakeLists.txt …
=> fix prebuilt error

tests/regression/mmedit.yml
Fix regression test image.
mmedit.yml
None.
None.
=> [Fix] fix mmedit test picture

configs/mmpose/pose-detection_sdk_static-256x192.py, mmdeploy/codebase/mmpose/deploy/pose_detection.py, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py, mmdeploy/codebase/mmseg/deploy/segmentation_model.py, tests/regression/mmpose.yml
support mmpose2.0 for sdk
None
=> support mmpose2.0 for sdk

tests/regression/mmcls.yml, tests/regression/mmdet.yml, tests/regression/mmedit.yml, tests/regression/mmocr.yml, tests/regression/mmpose.yml, tests/regression/mmrotate.yml, tests/regression/mmseg.yml, tools/regression_test.py
Fix regression_test.py
- update yaml files
- update regression_test.py 
tested codebases …
=> fix reg test for 2.0 

docs/en/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
补充一个参数“device”
Supplemental a parameter "device"
=>  Supplemental a parameter "device"

tests/regression/mmseg.yml, tools/regression_test.py
log cmd to log for regresstion test
update `tools/regresstion_test.py` to include cmd info to log for both running `deploy.py` and `test.py`
There are totally three output log files:
- `convert.log` is the log file of running `tools/deploy.py`
- `backend_test.log` is the log file of running `tools/test.py` with backend model file.
- `sdk_test.log` is the log file of running `tools/test.py` with sdk + backend model file.
```
2022-09-30 08:55:08,705 - mmdeploy - INFO - ----------------------------------------------------------------------------------------------------
2022-09-30 08:55:08,705 - mmdeploy - INFO - Start running cmd
python3 ./tools/deploy.py \ …
```
=> log cmd info for regresstion test

mmdeploy/pytorch/ops/layer_norm.py
Same as #1168 
Same as #1168 
None.
None.
=> [Fix 2.0] remove aten for torch1.12 on dev-1.x

.circleci/docker/Dockerfile, .circleci/test.yml, .github/workflows/backend-ncnn.yml, .github/workflows/backend-ort.yml, .github/workflows/backend-pplnn.yml, .github/workflows/backend-torchscript.yml, .github/workflows/build.yml, requirements/codebases.txt
mmcls v1.0.0rc2 now requires mmengine>=0.2.0 while mmdet v3.0.0rc1 requires mmengine <0.2.0, which leads a conflict on our ci.
None.
None.
3. If the modification has a dependency on downstream projects of a newer version, this PR should …
=> [Fix] Fix mmengine ci

mmdeploy/apis/calibration.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmpose/deploy/pose_detection.py
`create_input` function of some codebases (e.g. mmcls) cannot handle a list imgs input, which will failed in `profiler.py`.
Fix
None.
None. …
=> [Fix] Fix create input for dev-1.x

requirements/codebases.txt, tests/test_codebase/test_mmpose/test_mmpose_models.py
Fix mmpose msmu head unit test after release of `mmpose==1.0.0rc0`
1. requirments
2. ut
None
4. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
5. The documentation has been modified accordingly, like docstring or example tutorials.
=> Update msmu head UT of mmpose 

tools/regression_test.py
Fix https://github.com/open-mmlab/mmdeploy/issues/1135
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all …
=> fix comparison logic in regression test

mmdeploy/core/rewriters/symbolic_rewriter.py, tests/test_core/test_symbolic_register.py
Nightly PyTorch has remove `symblic_registry.register_op`. …
=> update symbolic rewriter

docs/en/04-supported-codebases/mmocr.md, docs/zh_cn/04-supported-codebases/mmocr.md, mmdeploy/apis/onnx/partition.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/core/optimizers/__init__.py, mmdeploy/core/optimizers/optimize.py
Remove opset_imports that were not used after ONNX extraction.
Before:
After:
=> remove imports

README.md, README_zh-CN.md
=> [Bug] side effect: fix badge display issue

.circleci/scripts/linux/build.sh, .circleci/test.yml
test_windows_onnxruntime workflow failed in circleci
1. Pre-commit or other linting tools are used …
=> fix test_windows_onnruntime workflow error in circleci

configs/mmseg/segmentation_ncnn-int8_static-1024x2048.py, docs/en/03-benchmark/quantization.md, docs/zh_cn/03-benchmark/quantization.md, mmdeploy/pytorch/functions/interpolate.py, mmdeploy/pytorch/ops/adaptive_pool.py
Add Fast-SCNN mmsgemention quantization evaluation result for ncnn
Implementation details：https://zhuanlan.zhihu.com/p/567319765
1. fix interpolate__ncnn bug
This may have rounding errors before modification
2. fix adaptive_avg_pool2d_ncnn bug
For ncnn, AdaptiveAvgPool2d doesn't seem to be equal to pytorch's nn.AdaptiveAvgPool2d when the output size is 1
3. Add Fast-SCNN mmsgemention quantization evaluation result for ncnn
No …
=> Add mmseg configs for compatibility with Fast-SCNN model in ncnn backend

mmdeploy/mmcv/cnn/__init__.py, mmdeploy/mmcv/cnn/conv2d_adaptive_padding.py, tests/regression/mmcls.yml
=> fix efficientnet from mmcls

mmdeploy/mmcv/ops/__init__.py
=> fix bev nms

tests/regression/mmcls.yml
=> update cls yaml

.circleci/test.yml, CMakeLists.txt, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version to 0.10.0

.circleci/scripts/windows/install_opencv.ps1
=> upate opencv that enables video build option

csrc/mmdeploy/apis/python/video_recognizer.cpp, docs/en/04-supported-codebases/mmaction2.md, docs/zh_cn/04-supported-codebases/mmaction2.md, mmdeploy/codebase/mmaction/deploy/video_recognition.py
fix some errors introduced by [PR1138](https://github.com/open-mmlab/mmdeploy/pull/1183)
=> [Fix] fix some errors introduced by pr1138

tests/regression/mmdet.yml, tools/regression_test.py
Fix regression test.
change the default test_pass to `False`
4. The …
=> fix reg test of dev-1.x

tests/test_codebase/test_mmdet3d/test_mmdet3d_models.py
Fix circle ci
if rewrite outputs be list, use outputs[0]
=> fix(circleci): rewrite outputs is a list

tests/regression/mmdet.yml
https://github.com/open-mmlab/mmdeploy/issues/1333
=> [Fix] Fix config name in mmdet yaml

docs/en/get_started.md, docs/zh_cn/get_started.md
make mmcv-full to  "mmcv>=2.0.0rc2"
https://github.com/open-mmlab/mmdeploy/issues/1290
=> [Fix] fix the mmcv version

docs/zh_cn/01-how-to-build/rockchip.md, tools/scripts/ubuntu_cross_build_rknn.sh
One of mmdeploy demo 'posetracker' introduces 'cv::VideoCapture' which requests OpenCV contains video modules.
But in rknn build scripts and its document, the adopted OpenCV lacks video modules. 
docs/zh_cn/01-how-to-build/rockchip.md
tools/scripts/ubuntu_cross_build_rknn.sh
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
=> build opencv for aarch64 with videoio enabled

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp, mmdeploy/mmcv/ops/roi_align.py, tests/test_ops/test_ops.py
Fix test ops.
multiclass nms and rotated multiclass nms will be fixed in other PR.
1. Update onnx2ncnn fuse pass
2. Custom ops for TensorRT
3. InstanceNorm disable cudnn …
=> [Fix] fix test ops

docs/en/04-supported-codebases/mmdet3d.md, docs/zh_cn/04-supported-codebases/mmdet3d.md, docs/zh_cn/04-supported-codebases/mmrotate.md, mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py, mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py, mmdeploy/codebase/mmdet3d/models/mvx_two_stage.py, mmdeploy/codebase/mmdet3d/models/pillar_scatter.py, tools/scripts/build_ubuntu_x64_pplnn.py
* Add mmdet3d doc
* Update mmdet3d docstring
* mmrotate typo
=> Add mmdet3d doc

tools/test.py
mmediting regression test failed because dataloader building has bugs.
tools/test.py
None.
None.
4. The documentation has been modified accordingly, like docstring or …
=> [Fix] Fix test for lattency

tests/regression/mmcls.yml
mobileone uses wrong config in regression test, ort deploy failed.
Use the deploy model config, not train model config.
None.
None. …
=> [Fix] fix mobileone regtest

mmdeploy/backend/sdk/export_info.py
Fix sdk export pipeline.json. 
The error is due to line 249
=> [FIX] Fix sdk export pipeline.json

docs/en/04-supported-codebases/mmdet3d.md, docs/zh_cn/04-supported-codebases/mmdet3d.md
trt8.2/cu11+trt8.4 may fails for mmdet3d models
update doc for known issues
=> Improve mmdet3d doc

mmdeploy/apis/onnx/export.py, mmdeploy/apis/pytorch2onnx.py, requirements/runtime.txt, tests/regression/mmdet.yml, tools/regression_test.py
=> Fix some bugs on dev1.x

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Yolov5-p6 has wrong answer because of wrong `pad_params` value when `scale_factor` values are not 1.
pad_params should divide by scale_factors
None.
```bash
python tools/test.py ../mmyolo/configs/deploy/detection_tensorrt-fp16_dynamic-192x192-1344x1344.py ../mmyolo/configs/yolov5/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco.py --model yolov5-p6-fp32/end2end.engine  --device cuda:0
```
2. The modification is covered by complete unit tests. If …
=> [Fix] Fix yolov5 p6

docs/zh_cn/02-how-to-run/write_config.md
=> [Docs]fix bad links in Master Branch

csrc/mmdeploy/backend_ops/onnxruntime/grid_sample/grid_sample.cpp, csrc/mmdeploy/backend_ops/onnxruntime/grid_sample/grid_sample.h, csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp, csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.h, csrc/mmdeploy/backend_ops/onnxruntime/nms_rotated/nms_rotated.cpp, csrc/mmdeploy/backend_ops/onnxruntime/nms_rotated/nms_rotated.h, csrc/mmdeploy/net/ort/ort_net.cpp
Replace unsupported API usage when onnxruntime>=1.13 is detected.
None.
3. If the modification has a dependency on downstream …
=> [Fix] Support onnxruntime-1.13

docs/en/02-how-to-run/quantize_model.md, docs/zh_cn/02-how-to-run/quantize_model.md, tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/build_ubuntu_x64_ort.py, tools/scripts/build_ubuntu_x64_pplnn.py, tools/scripts/build_ubuntu_x64_torchscript.py, tools/scripts/ubuntu_cross_build_aarch64.sh, tools/scripts/ubuntu_cross_build_rknn.sh
fix scripts and doc.
* Scripts add pathlib to locate `~` symbol
* Docs rewrite
* Build OCV with TIFF instead of system lib dependency
1. Pre-commit or other …
=> fix(tools/scripts): find env file failed

docs/en/02-how-to-run/profile_model.md, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py, mmdeploy/codebase/mmedit/deploy/super_resolution.py, mmdeploy/codebase/mmocr/deploy/text_detection.py, mmdeploy/codebase/mmocr/deploy/text_recognition.py, mmdeploy/codebase/mmpose/deploy/pose_detection.py, mmdeploy/codebase/mmrotate/deploy/rotated_detection.py, mmdeploy/codebase/mmseg/deploy/segmentation.py, tests/regression/mmcls.yml, tests/regression/mmdet.yml, tests/regression/mmdet3d.yml, tests/regression/mmedit.yml, tests/regression/mmocr.yml, tests/regression/mmpose.yml, tests/regression/mmrotate.yml, tests/regression/mmseg.yml, tools/regression_test.py, tools/test.py
Update regresssion test to parse eval result from json
None
=> Update regresssion test to parse eval result from json

mmdeploy/core/rewriters/symbolic_rewriter.py, tests/test_core/test_symbolic_register.py
https://github.com/open-mmlab/mmdeploy/pull/1122
1. Pre-commit or other linting tools are used to …
=> update symbolic rewriter 1.x

README.md, README_zh-CN.md, docs/en/04-supported-codebases/mmaction2.md
fix type and add link to README.md
=> [Fix] fix mmaction2 docs(dev-1.x)

tests/regression/mmseg.yml, tools/regression_test.py
1. give model path instead of 'x' when conversion fails for parsing running logs.
3. If the modification has a dependency on downstream projects of a newer version, this PR …
=> update reg test

README.md, README_zh-CN.md, docs/en/04-supported-codebases/mmaction2.md, docs/zh_cn/04-supported-codebases/mmaction2.md
fix type and add link to README.md
=> [Fix] fix mmaction2 docs

csrc/mmdeploy/apis/python/detector.cpp, csrc/mmdeploy/apis/python/restorer.cpp, csrc/mmdeploy/apis/python/segmentor.cpp
Wrap destructors of C API results using `std::shared_ptr` and `py::capsule`. …
=> [Enhancement] Avoid copying dense arrays in Python API

tests/regression/mmcls.yml
=> regression cls yaml

mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py
=> fix yolov3 trt8.2 1.x

csrc/mmdeploy/preprocess/transform/pad.cpp
logical_or will not be initialized if it is not in the pipeline, which leads to error on some config. …
=> [Fix] Fix pad with logical_or

mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py
master version of https://github.com/open-mmlab/mmdeploy/pull/1425 …
=> [Fix] fix yolohead trt8.2

mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/pytorch/functions/topk.py
Yolox use pad mode `pad_to_square`, which is conflict with current object detection task preprocess. …
=> fix pad to square

tests/regression/mmseg.yml, tools/regression_test.py
* give model path if stead of 'x' when conversion failed
* set --models with default value ['all']
* fix mmseg yml …
=> update reg test (#1417)

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp, csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.h, csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
The same as #1430 
Same as #1430 
None.
None.
=> [Fix] fix ncnn torch 1.12 dev-1.x

csrc/mmdeploy/core/profiler.cpp, csrc/mmdeploy/graph/cond.cpp, csrc/mmdeploy/graph/cond.h, csrc/mmdeploy/graph/inference.cpp, csrc/mmdeploy/graph/static_router.cpp, csrc/mmdeploy/graph/static_router.h, tools/sdk_analyze.py
=> [Enhancement] refactor profiler

mmdeploy/pytorch/functions/topk.py
Static onnx detector with GPU will suffer from const-fold issue. …
=> [Fix] Avoid gpu topk const-fold

mmdeploy/codebase/base/backend_model.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, tests/test_codebase/test_mmdet/test_object_detection_model.py
=> [Fix] fix visualization for partition

tools/sdk_analyze.py
fix condition
``` 
detector_apply
sleep(1hour)
detector_apply
```
=> [Fix] Fix profiler

docs/en/01-how-to-build/cross_build_ncnn_aarch64.md, docs/en/02-how-to-run/quantize_model.md, docs/zh_cn/01-how-to-build/cross_build_ncnn_aarch64.md, docs/zh_cn/02-how-to-run/quantize_model.md, tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/build_ubuntu_x64_ort.py, tools/scripts/build_ubuntu_x64_pplnn.py, tools/scripts/build_ubuntu_x64_torchscript.py, tools/scripts/ubuntu_cross_build_aarch64.sh, tools/scripts/ubuntu_cross_build_rknn.sh
fix script install error.
cherry-pick  https://github.com/open-mmlab/mmdeploy/pull/1385 to dev-1.x branch.
=> fix(tools/scripts): missing `expanduser`

.github/workflows/backend-ncnn.yml, docs/en/01-how-to-build/android.md, docs/en/01-how-to-build/cross_build_ncnn_aarch64.md, docs/zh_cn/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/cross_build_ncnn_aarch64.md, tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/ubuntu_cross_build_aarch64.sh
fix ncnn script install
* update CI to ncnn-20221128 version
* update doc
* update github action trigger
4. The documentation has been modified accordingly, like …
=> fix(CI): ncnn script install

docker/CPU/Dockerfile, docker/GPU/Dockerfile
=> [Fix] fix dockerfile

mmdeploy/pytorch/ops/gelu.py
=> [Fix] fix gelu torch>1.12

demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/01-how-to-build/macos-arm64.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version v0.11.0

CMakeLists.txt
=> [Fix]: Change version in cmakelists

docker/CPU/Dockerfile, docker/GPU/Dockerfile
When using `USE_SRC_INSIDE=true` the pip source still the original. Since the user want to use `USE_SRC_INSIDE` so we need to switch the source of pip as well
Add pip source. And speed up the download for pip . 🚀
=> [Improve] Improve dockerfile pip source

mmdeploy/codebase/base/mmcodebase.py, mmdeploy/codebase/base/task.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py, mmdeploy/codebase/mmseg/deploy/segmentation_model.py
The warning is super annoying!
add scope config so the Codebase and Task will be searched in `mmdeploy` scope.
Since the backend model will try to build the data preprocessor in the origin codebase, the warning of it has not been removed. You can set the parent scope as below, but I am afraid of potential risk.
```python
from mmdet.models import DETECTORS
__BACKEND_MODEL = Registry('backend_detectors')
....
def build_object_detection_model(
model_files: Sequence[str],
model_cfg: Union[str, Config],
deploy_cfg: Union[str, …
```
=> [Enhancement] Suppress mmengine scope warning

docker/CPU/Dockerfile, docker/GPU/Dockerfile
When using `USE_SRC_INSIDE=true` the pip source still the original. Since the user want to use `USE_SRC_INSIDE` so we need to switch the source of pip as well
Add pip source. And speed up the download for pip . 🚀 
Is a copy PR #1484 for master branch
=> [Enhancement] Add pip source in dockerfile for `master` branch

mmdeploy/apis/visualize.py, mmdeploy/backend/base/base_wrapper.py, mmdeploy/backend/onnxruntime/wrapper.py, mmdeploy/backend/tensorrt/init_plugins.py, mmdeploy/backend/tensorrt/onnx2tensorrt.py, mmdeploy/backend/tensorrt/wrapper.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmcls/deploy/classification_model.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmdet/models/backbones.py, mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py, mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py, mmdeploy/codebase/mmdet/models/dense_heads/yolox_head.py, mmdeploy/codebase/mmocr/deploy/text_recognition.py, mmdeploy/codebase/mmrotate/models/roi_heads/gv_ratio_roi_head.py, mmdeploy/codebase/mmrotate/models/roi_heads/oriented_standard_roi_head.py, mmdeploy/core/optimizers/function_marker.py, mmdeploy/core/rewriters/symbolic_rewriter.py, tests/test_ops/test_ops.py, tools/deploy.py
Fix strings ends with `\`
`\` would be treated as `tab` in string …
=> [Fix] Fix multiline string

csrc/mmdeploy/apis/c/mmdeploy/common.cpp, csrc/mmdeploy/apis/c/mmdeploy/common.h, csrc/mmdeploy/apis/cxx/mmdeploy/common.hpp, csrc/mmdeploy/core/CMakeLists.txt, csrc/mmdeploy/core/profiler.cpp, csrc/mmdeploy/core/profiler.h, csrc/mmdeploy/graph/cond.cpp, csrc/mmdeploy/graph/cond.h, csrc/mmdeploy/graph/inference.cpp, csrc/mmdeploy/graph/static_router.cpp, csrc/mmdeploy/graph/static_router.h, csrc/mmdeploy/graph/task.cpp, csrc/mmdeploy/graph/task.h, csrc/mmdeploy/net/net_module.cpp, csrc/mmdeploy/preprocess/transform/compose.cpp, csrc/mmdeploy/preprocess/transform/compose.h, demo/csrc/c/det_cls.cpp, third_party/concurrentqueue/concurrentqueue.h, tools/sdk_analyze.py
=> Sync profiler

.circleci/test.yml, .github/workflows/build.yml, mmdeploy/codebase/mmcls/models/classifiers/base.py, requirements/codebases.txt, requirements/runtime.txt
=> [Fix]: fix requirements of mmedit

.github/workflows/stable.yml
add stable workflow to check issue and PR
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
=> [Feat]: add stable workflow to check issue and PR

mmdeploy/codebase/mmdet/models/layers.py, mmdeploy/mmcv/ops/nms.py
=> [FIX] recovery mmdet layers

csrc/mmdeploy/net/ppl/ppl_net.cpp, docs/en/05-supported-backends/pplnn.md, docs/zh_cn/05-supported-backends/pplnn.md, tools/scripts/build_ubuntu_x64_pplnn.py
ppl.nn 0.9.0 has some minor changes on c++ api.
update docs about supported version of ppl.nn and remove deprecated calls.
releases before 0.9.0 are not supported after this pr
none
=> update pplnn to 0.9.1

csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv.cpp, csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu, mmdeploy/backend/tensorrt/__init__.py, mmdeploy/backend/tensorrt/torch_allocator.py, mmdeploy/backend/tensorrt/utils.py, mmdeploy/backend/tensorrt/wrapper.py
Sync #1493 feature on dev-1.x branch
-[x] Add allocator for trt
-[x] Fix DCNv2 trt implementation, which solved #972 in dev-1.x.
None.
Same to #1493 
4. The documentation …
=> [Improvement]  Add allocator for trt and fix DCNv2 trt implementation on dev-1.x

docs/en/index.rst, docs/zh_cn/index.rst
=> Add mmaction2 & coreml sphinx-doc link.

csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.cpp, mmdeploy/pytorch/symbolics/squeeze.py
=> [Fix] fix squeeze export and unsqueeze pass for opset 13

csrc/mmdeploy/codebase/mmaction/cuda/transpose.cu
=> [Fix] 'mmaction2::transpose.cu' build failed on cuda-10.2

mmdeploy/mmcv/ops/modulated_deform_conv.py, tests/test_mmcv/test_mmcv_ops.py
=> torchjit mdcn 1.x

mmdeploy/backend/sdk/export_info.py
=> add is_batched argument to pipeline.json

requirements/readthedocs.txt
APIs are not rendered successfully in https://mmdeploy.readthedocs.io/en/dev-1.x/api.html
add 'mmengine' in readthedocs.txt …
=> Fix api build error in readthedocs

configs/mmrotate/rotated-detection_tensorrt-fp16_static-1024x1024.py, docs/en/04-supported-codebases/mmrotate.md, docs/zh_cn/04-supported-codebases/mmrotate.md, mmdeploy/codebase/mmrotate/models/dense_heads/__init__.py, mmdeploy/codebase/mmrotate/models/dense_heads/rotated_rtmdet_head.py, tests/test_codebase/test_mmrotate/test_mmrotate_models.py
Support RTMDet-R deployment in MMRotate dev-1.x
1. Pre-commit or other linting tools are used to …
=> [Feature] Support RTMDet-R deployment

docs/en/07-developer-guide/support_new_backend.md, docs/zh_cn/07-developer-guide/support_new_backend.md
=> [Refactor] Update support_new_backend.md

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp, mmdeploy/mmcv/ops/roi_align.py, tests/test_ops/test_ops.py
test_op.py on master branch has seg-fault error.
Cherry-pick #1352 to master branch.
None.
None.
4. The documentation has been modified accordingly, like docstring or …
=> Cherry-pick #1352 to fix ops unittest seg-fault error

mmdeploy/apis/visualize.py, mmdeploy/codebase/mmdet/models/roi_heads/test_mixins.py, tools/deploy.py
Solve #1565 
1. Fix `mask_test_mixin__simple_test_mask` broadcast for multi-batch case
2. Make deploy.py support list of img and test_img inputs.
None.
#1565
4. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
5. The …
=> [Fix] Fix Mask R-CNN for multi-batch

mmdeploy/apis/visualize.py, mmdeploy/codebase/mmdet/models/roi_heads/standard_roi_head.py, tools/deploy.py
Same as #1575 
1. Fix broadcast for multi-batch on `standard_roi_head__predict_mask` function.
2. Fix multi-batch for imgs and test_imgs in `deploy.py`
None
Same as #1575 
4. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> [Fix] Fix Mask R-CNN for multi-batch on dev-1.x

mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmcls/deploy/classification_model.py, mmdeploy/codebase/mmcls/models/classifiers/base.py, tests/test_codebase/test_mmcls/test_mmcls_models.py
=> Add softmax to cls model

CMakeLists.txt, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version to v0.12.0

CMakeLists.txt, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version to v1.0.0rc1

demo/csrc/cpp/pose_tracker.cpp
=> [Fix] Fix debug build for PoseTracker 

docs/en/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/android.md
Now sdk should use static libs on android platform.
01-how-to-build/android.md
None.
None.
4. The documentation has been modified accordingly, like docstring or example …
=> [Doc] Fix Android build doc on master branch

tools/profiler.py
=> [Fix] fix no test_step error in TorchWrapper

.github/release.yml
Support auto generate release note.
1. Pre-commit or other linting tools are used to fix the …
=> [Improvement] Support auto release note

tools/regression_test.py
update log extension to `.txt` so that could be directly viewed in browser.
1. Pre-commit or other …
=> [Improvement]: update log ext in regression test

mmdeploy/apis/visualize.py
When the img arg of visualize api is a string, it is also a Sequence, so it will not to change to a list, which will have bugs.
`if not isinstance(img, Sequence):` -> `if not isinstance(img, list):`
None.
None.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all …
=> [Fix] Fix visualize api bug

requirements/codebases.txt
People often says "why `register_all_modules` fails on mmdeploy+mmedit ?", 
They have no idea about the break change from openmmlab2.0
* fix version confilict with openmmlab 2.0
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> fix(requirements): codebase version

tools/regression_test.py
=> cherry-pick 1608

mmdeploy/apis/visualize.py, mmdeploy/codebase/base/task.py
=> [Fix] fix headless device visualize

.circleci/test.yml, .github/workflows/build.yml
MMDeploy code update may impact mmyolo. Add the ci to check whether mmyolo is failed or not.
None.
It is trigged when there is a new pr. …
=> [Enhancement] Add mmyolo CI on mmdeploy

docs/en/01-how-to-build/build_from_source.md, docs/zh_cn/01-how-to-build/build_from_source.md
=> [Docs] Correct document errors in `build_from_source.md`  master -> 1.x 

mmdeploy/codebase/mmaction/deploy/video_recognition.py
1. skip visualize if not install `decord` or `moviepy`
2. fix visualize score
=> [Fix] fix mmaction2 visualizer

mmdeploy/backend/tensorrt/torch_allocator.py
=> [Fix] fix torch allocator resouce releasing

mmdeploy/codebase/mmocr/deploy/text_recognition.py
=> [Fix] fix mmocr create input from np.ndarray

csrc/mmdeploy/net/net_module.cpp
* refactor `NetModule`
* name
* fix sorting
* fix indices
(cherry picked from commit f5a05b52191e19d67225f332c19dfd53dac55843)
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …
=> [Refactor] Support batch inference with shape clustering (#1668)

configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py, configs/mmpose/pose-detection_simcc_tensorrt-fp16_dynamic-256x192.py, configs/mmpose/pose-detection_simcc_tensorrt_dynamic-256x192.py
There is no tensorrt-fp16 deployment config for simcc
Add `configs/mmpose/pose-detection_simcc_tensorrt_dynamic-256x192.py` …
=> [Enhancement] check in tensorrt-fp16 deployment config for simcc

csrc/mmdeploy/backend_ops/tensorrt/instance_norm/trt_instance_norm.cpp
=> [Fix] fix instance norm double free

csrc/mmdeploy/backend_ops/tensorrt/instance_norm/trt_instance_norm.cpp
=> [fix] Fix double free 1.x

mmdeploy/core/optimizers/optimize.py
IndexError: list index out of range error as `model.opset_import list` is changing dynamically
If this PR …
=> Fix bug in remove_imports

csrc/mmdeploy/apis/cxx/mmdeploy/text_recognizer.hpp, csrc/mmdeploy/codebase/mmocr/warp.cpp, csrc/mmdeploy/utils/opencv/opencv_utils.cpp, demo/csrc/cpp/utils/visualize.h
(cherry picked from commit cadc2658f352bd319c81f1dc0b7411827b6ca840)
If this PR introduces a new feature, it is …
=> Fix `WarpBbox` and memory leak in `TextRecognizer` (#1745)

cmake/cuda.cmake, cmake/tensorrt.cmake
…a versions. (#1740)
* update cmake
* typos
=> Cherry pick PR 1740 to dev-1.x 

CMakeLists.txt, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version to v0.13.0

demo/csrc/cpp/utils/palette.h
=> [Fix] Fix palette generation on opencv-3.x

csrc/mmdeploy/apis/c/mmdeploy/classifier.cpp, csrc/mmdeploy/apis/c/mmdeploy/detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/pipeline.cpp, csrc/mmdeploy/apis/c/mmdeploy/pipeline.h, csrc/mmdeploy/apis/c/mmdeploy/pose_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp, csrc/mmdeploy/apis/c/mmdeploy/rotated_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp, csrc/mmdeploy/apis/c/mmdeploy/text_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.cpp, csrc/mmdeploy/apis/c/mmdeploy/video_recognizer.cpp, csrc/mmdeploy/core/model.cpp, csrc/mmdeploy/core/model.h, csrc/mmdeploy/core/model_impl.h, csrc/mmdeploy/graph/inference.cpp, csrc/mmdeploy/model/CMakeLists.txt, csrc/mmdeploy/model/directory_model_impl.cpp, csrc/mmdeploy/model/zip_model_impl.cpp
(cherry picked from commit eb75bee9218cf4f3958590efc7e91a9136236004)
If this PR introduces a new feature, it is …
=> add `Model::ReadConfig` & simplify handle creation (#1738)

mmdeploy/backend/tensorrt/utils.py
pycuda should be inited before we create the builder. …
=> [Fix] Fix tensorrt int8

csrc/mmdeploy/core/mpl/type_traits.h
=> [Fix] Fix missing include for gcc-10 build

csrc/mmdeploy/apis/cxx/CMakeLists.txt
=> [Fix] Avoid linking static libs in monolithic build

csrc/mmdeploy/core/mpl/type_traits.h
(cherry picked from commit f78a4526812f5d696bb784dd475021fea6c292be)
If this PR introduces a new feature, it is …
=> [Fix] Fix missing include for gcc-10 build (#1802)

csrc/mmdeploy/preprocess/transform/default_format_bundle.cpp, csrc/mmdeploy/preprocess/transform/pad.cpp, mmdeploy/codebase/mmdet/models/__init__.py, mmdeploy/codebase/mmdet/models/utils/__init__.py, mmdeploy/codebase/mmdet/models/utils/gaussian_target.py, tests/test_codebase/test_mmdet/test_mmdet_utils.py
=> [Fix] fix centernet

docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
Found some errors when testing SDK prebuilt package.
Bump version to get a new prebuilt package for `pose_tracker` application
If this PR introduces a new feature, it is better to list some use cases here, …
=> bump version to 1.0.0rc3

csrc/mmdeploy/core/registry.h
=> [Fix] Fix Debian aarch64 cross compiling

mmdeploy/codebase/mmocr/models/text_detection/fpn_cat.py
=> mmocr FPNC neck support asf module

mmdeploy/codebase/mmdet/deploy/utils.py
Clip failed on TensorRT 8.0
1. Pre-commit or other linting tools are used to fix the potential …
=> [Fix] Fix clip on tensorrt 8.0

csrc/mmdeploy/codebase/mmcls/linear_cls.cpp
* add softmax in cls postprocess
* minor
(cherry picked from commit bcb93ead589e6103377b1f8d6cfdc8f5f24b9527)
If …
=> [Enhancement] Add optional `softmax` in `LinearClsHead`  (#1858)

README.md, README_zh-CN.md
highlight version problem.
update readme.
=> docs(project): highlight version

mmdeploy/codebase/base/task.py, tests/regression/mmcls.yml
MobileOne has wrong result.
We should use the official config and checkpoint, and then open switch_to_deploy to open MobileOne deploy mode.
[Please refer](https://mmclassification.readthedocs.io/en/dev-1.x/papers/mobileone.html#how-to-use)
Check whether the model backbone has `switch_to_deploy`, if so, open it in `build_pytorch_model`.
None.
None.
2. The modification is covered by complete unit tests. If not, please add more unit tests to …
=> [Fix] Fix MobileOne deployment.

mmdeploy/backend/tensorrt/utils.py
logger.warning failed during trt conversion
use mmdeploy logger
=> [Fix] Fix the warning method that calls the trt logger

mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py
[bug-report](https://openmmlab-deploee.oss-cn-shanghai.aliyuncs.com/tmp/convert_model/error/ffe746.txt)
Add necessary concat for dummy ops.
None.
Please use cuda:0 for inference, cpu version will fix in mmdet by @RangiLyu 
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested …
=> [Fix] Fix RTMDet-Ins head deploy

csrc/mmdeploy/codebase/mmpose/keypoints_from_heatmap.cpp
=> [Enhancement] optimize mmpose postprocess

.gitignore, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Context.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Device.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/DisposableObject.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Model.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/PoseTracker.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Profiler.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/RotatedDetector.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Scheduler.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/TextDetector.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/common.cs, csrc/mmdeploy/apis/csharp/MMDeploy/NativeAPIs/NativeMethods_c_api.cs, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.cpp, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.hpp, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cu, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cuh, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.hpp, demo/csharp/Demo.sln, demo/csharp/pose_tracker/Program.cs, demo/csharp/pose_tracker/pose_tracker.csproj, demo/csharp/rotated_detection/Program.cs, demo/csharp/rotated_detection/rotated_detection.csproj
sync https://github.com/open-mmlab/mmdeploy/pull/1718
=> [Sync] Sync csharp api to dev-1.x 

docs/en/07-developer-guide/regression_test.md
=> [Fix] fix typo in docs/en/07-developer-guide/regression_test.md

.github/workflows/stale.yml
=> [Fix]: update stale workflow

configs/mmpose/pose-detection_simcc_coreml_static-256x192.py
Add rtmpose coreml support
Add ./mmdeploy/configs/mmpose/pose-detection_simcc_coreml_static-256x192.py
1. Pre-commit or other linting tools are used to fix the …
=> add rtmpose coreml support

.github/release.yml, .github/workflows/prebuild.yml, docker/prebuild/Dockerfile, docs/en/get_started.md, docs/zh_cn/get_started.md
Update dockerfile and add github release note
- Update prebuild dockerfile
- Add github release note yml
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
=> [Enhancement]: Update dockerfile and add github release note

.github/workflows/backend-rknn.yml, .github/workflows/build.yml, tools/scripts/ubuntu_cross_build_aarch64.sh, tools/scripts/ubuntu_cross_build_rknn.sh
=> Fix rknn and aarch64 build ci

docs/en/04-supported-codebases/mmseg.md, docs/zh_cn/04-supported-codebases/mmseg.md
=> [Docs]update mmseg docs

README.md, README_zh-CN.md
=> Update Repo List in README

.github/workflows/build.yml, .github/workflows/quantize.yml, mmdeploy/codebase/mmseg/deploy/segmentation.py, mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py, requirements/codebases.txt, requirements/optional.txt
Fix https://github.com/open-mmlab/mmdeploy/issues/1979
fix mmseg exportation for `out_channels=1`
None
=> [Fix]: fix mmseg exportation for out_channels=1

mmdeploy/codebase/mmseg/deploy/segmentation.py
Fix `with_argmax` not exported to `pipeline.json` for mmseg, #2050 
None
=> fix with_argmax for mmseg

CMakeLists.txt, csrc/mmdeploy/apis/csharp/README.md, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_runtime/version.py
=> bump version to v1.1.0

mmdeploy/core/rewriters/function_rewriter.py
=> fix function rewriter

.github/workflows/prebuild.yml, tools/package_tools/mmdeploy_builder.py
1. Fix loading `mmdeploy.so.{MAJOR}`
2. Support triggering prebuild workflow manually.
4. If the modification has a dependency on downstream projects of a newer version, …
=> fix prebuild

.github/workflows/prebuild.yml, .github/workflows/publish.yml, tools/package_tools/test/test_sdk.ps1, tools/package_tools/test/test_sdk_python.ps1, tools/package_tools/test/test_sdk_python.sh
=> fix prebuild uploading

README.md, README_zh-CN.md
Add introduction to deploee.
Update REAME.
2. The modification is covered by …
=> docs(project): deploee introduction

csrc/mmdeploy/codebase/mmseg/segment.cpp
address https://github.com/open-mmlab/mmdeploy/issues/2116
=> [Fix] fix mmseg output sync

docs/en/03-benchmark/benchmark.md, docs/en/04-supported-codebases/mmpretrain.md, docs/zh_cn/03-benchmark/benchmark.md, docs/zh_cn/04-supported-codebases/mmpretrain.md, mmdeploy/codebase/mmpretrain/deploy/classification.py, tests/regression/mmpretrain.yml
=> Fit for MMPretrain EfficientFormer

.github/workflows/docker.yml, docker/Release/Dockerfile, docs/en/01-how-to-build/build_from_docker.md, docs/zh_cn/01-how-to-build/build_from_docker.md, requirements/backends.txt
=> update document for docker installation

mmdeploy/mmcv/ops/nms.py
=> Fix NMS Return Index

CMakeLists.txt, csrc/mmdeploy/codebase/mmcls/CMakeLists.txt, csrc/mmdeploy/codebase/mmdet/CMakeLists.txt, csrc/mmdeploy/codebase/mmedit/CMakeLists.txt, csrc/mmdeploy/codebase/mmpose/CMakeLists.txt, docs/en/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/android.md
- move CMAKE_BUILD_TYPE check before project (otherwise the CMAKE_BUILD_TYPE will be set to RelWithDebInfo)
- add -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False
=> [Fix] fix mmdeploy android library size

docs/en/sdk_usage/index.rst, docs/en/sdk_usage/profiler.md, docs/zh_cn/sdk_usage/index.rst, docs/zh_cn/sdk_usage/profiler.md
=> add sdk profiler docs

cmake/MMDeploy.cmake, csrc/mmdeploy/apis/c/CMakeLists.txt, csrc/mmdeploy/backend_ops/onnxruntime/CMakeLists.txt, csrc/mmdeploy/model/CMakeLists.txt, tools/package_tools/generate_build_config.py
- using ExternalProject to build zlib and libzip
- add rpath to net module in case onnxruntime cannot be found
=> [Feature] Enable read zip model in prebuild package.

csrc/mmdeploy/codebase/mmocr/attention_convertor.cpp, csrc/mmdeploy/codebase/mmocr/base_convertor.cpp, csrc/mmdeploy/codebase/mmocr/base_convertor.h, csrc/mmdeploy/codebase/mmocr/crnn.cpp, mmdeploy/codebase/mmocr/deploy/text_recognition.py
address https://github.com/open-mmlab/mmdeploy/issues/2190
- fix Dictionary param export && add BaseTextRecogPostprocessor params
- sync sdk ctc_convertor with pytorch
=> [Fix] Fix text recog task postprocess

CMakeLists.txt, csrc/mmdeploy/apis/csharp/README.md, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/01-how-to-build/build_from_docker.md, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/01-how-to-build/build_from_docker.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_runtime/version.py
bump version to v1.2.0
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> bump version to v1.2.0

docs/en/04-supported-codebases/mmpose.md, docs/zh_cn/04-supported-codebases/mmpose.md
=> [Docs] Fix yolox-pose link

docs/en/get_started.md, docs/zh_cn/get_started.md
=> the c++ code in get_started docs

docs/zh_cn/05-supported-backends/onnxruntime.md, docs/zh_cn/05-supported-backends/tensorrt.md
=> [CodeCamp2023-553]翻译ort/trt后端编译中文文档

mmdeploy/pytorch/functions/multi_head_attention_forward.py
Fix https://github.com/open-mmlab/mmdeploy/issues/2318#issuecomment-1667003214
=> add kwargs to _scaled_dot_product_attention__tensorrt

demo/csrc/cpp/classifier.cxx, demo/csrc/cpp/detector.cxx, demo/csrc/cpp/pose_detector.cxx, demo/csrc/cpp/restorer.cxx, demo/csrc/cpp/rotated_detector.cxx, demo/csrc/cpp/segmentor.cxx, tools/scripts/build_ubuntu_x64_ncnn.py
fix bad profiling result.
add warmup
=> fix(demo): add warmup for wrong profiling result

README_zh-CN.md
=> Update QR Code

docs/en/01-how-to-build/macos-arm64.md, docs/en/05-supported-backends/coreml.md, docs/zh_cn/01-how-to-build/macos-arm64.md, docs/zh_cn/05-supported-backends/coreml.md, mmdeploy/backend/coreml/ops.py
fix mmdet export with pytorch 2.0
add torch_alias
=> fix mmdet export for coreml backend

csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp, demo/csrc/c/object_detection.cpp, demo/csrc/cpp/utils/visualize.h, demo/python/object_detection.py, docs/en/07-developer-guide/regression_test.md, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py, mmdeploy/mmcv/ops/nms.py, tests/regression/mmdet.yml
=> [Fix]: fix rtmdet-inst sdk

.github/workflows/lint.yml, docs/en/01-how-to-build/linux-x86_64.md, docs/zh_cn/01-how-to-build/linux-x86_64.md
add more build example for deploee.
update doc.
=> docs(build): add more example

csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp
ORT DBNet with mdcn accelerated from 175s to 6.7s.
=> refine gemm in ort mdcn

csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp, csrc/mmdeploy/backend_ops/onnxruntime/nms_rotated/nms_rotated.cpp
=> Fix ONNX Runtime Op memory leak

csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp, csrc/mmdeploy/preprocess/transform/compose.cpp
address https://github.com/open-mmlab/mmdeploy/issues/2380
=> Fix sdk error for multi-gpu execution

mmdeploy/codebase/mmagic/__init__.py, mmdeploy/codebase/mmagic/deploy/__init__.py, mmdeploy/codebase/mmagic/deploy/mmagic.py, mmdeploy/codebase/mmagic/deploy/super_resolution.py, tools/elena/extract_transform.py
I only renamed `mmedit` to `mmagic` for naming consistency.
1. …
=> Rename MMEdit to MMagic

docs/en/04-supported-codebases/mmdet.md, docs/zh_cn/04-supported-codebases/mmdet.md, tests/test_codebase/test_mmdet/test_mmdet_models.py
Add CondInst ut and update docs.
Add CondInst ut and update docs.
2. The …
=> add condinst ut & update docs

tools/package_tools/generate_build_config.py
Fixes open-mmlab/mmdeploy#2493
in generate_build_config.py in package_tools change "wheel platform tag" to <any> for "system flag" <jetson> …
=> Roman duris/fix jetson wheel platform

mmdeploy/backend/onnxruntime/init_plugins.py, mmdeploy/backend/onnxruntime/wrapper.py
fix https://github.com/open-mmlab/mmdeploy/issues/2556
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all …
=> fix ort wrapper

mmdeploy/mmcv/ops/nms.py
This pull request is related to https://github.com/open-mmlab/mmdeploy/issues/2571.
=> Fix for mask dimensions mismatch in rtmdet-ins models after exporting to ONNX

CMakeLists.txt, csrc/mmdeploy/apis/csharp/README.md, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_runtime/version.py
bump version to v1.13.1
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> bump version to v1.13.1
