open-mmlab/mmdeploy

csrc/preprocess/cuda/resize_impl.cpp
#40 adds support for ppl.cv 0.6, but it breaks builds using ppl.cv < 0.6; This PR brings back support for ppl.cv prior to 0.6.
No
3. If the modification has a …
=> Refactor cuda resize

docs/en/backends/ncnn.md
The ncnn version is set to 20211208. Most of feature in mmdeploy v0.1.0 are based on ncnn 20211208.
Change the docs for how to install 20211208 version ncnn.
None.
None. …
=> [Documents] ncnn version fix at 1208.

mmdeploy/codebase/mmdet/deploy/object_detection_model.py, tests/test_codebase/test_mmdet/test_object_detection_model.py
#22 : We cannot get the `CLASSES` of custom dataset in MMDet.
Modify `object_detection_model.py::get_classes_from_cfg`.
=> [Fix] Support MMDet custom dataset

mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
Related to issue #44 
Dynamic shape is mistaken as static shape in `mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py:39`
https://github.com/open-mmlab/mmdeploy/blob/03e1213848edbfc1d242f64b13372bc512871f6e/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py#L38
change to right logic
None
=> [Fix]: dynamic shape not valid in mmseg

tests/test_codebase/test_mmdet/test_mmdet_models.py
Add L2Norm unittest for default backend, which rewriter used in SSD neck.
tests/test_codebase/test_mmdet/test_mmdet_models.py.
None.
None. …
=> [Unittest] Add L2Norm unittest for default backend.

mmdeploy/codebase/mmdet/models/necks.py
TensorRT 7 does not support dynamic clamp, which is used in `torch.nn.functional.normalize`.
=> [Fix] Fix TensorRT 7 SSD

mmdeploy/core/rewriters/module_rewriter.py, mmdeploy/core/rewriters/rewriter_manager.py, tests/test_core/test_module_rewriter.py
When `patch_model`, we have to deepcopy a model, which increases the memory overhead.
Remove `deepcopy` and add comments.
=> [Enhancement]: Remove deepcopy in patch_model

mmdeploy/backend/openvino/wrapper.py, mmdeploy/utils/device.py, tests/test_utils/test_util.py, tools/test.py
It was found that `tools/test.py` with argument `--device cpu` crashes with the following error:
```bash
2022-01-11 01:45:25,318 - mmdeploy - INFO - Successfully loaded onnxruntime custom ops from             /home/sbevzyuk/mmdeployment_dir/MMDeploy/build/lib/libmmdeploy_onnxruntime_ops.so
Traceback (most recent call last):
File "/home/sbevzyuk/mmdeployment_dir/MMDeploy/tools/test.py", line 141, in <module>
main()
File "/home/sbevzyuk/mmdeployment_dir/MMDeploy/tools/test.py", line 112, in main
model = MMDataParallel(model, device_ids=[device_id])
File "/home/sbevzyuk/anaconda3/envs/mmdeployment/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 35, in __init__
super(MMDataParallel, self).__init__(*args, dim=dim, **kwargs)
File …
```
=> [Fix] Fixed device_id in tools/test.py for the CPU.

csrc/apis/c/detector.cpp, csrc/codebase/common.h, csrc/codebase/mmdet/object_detection.cpp
Find memory leak when testing SDK by enabling ASAN
1. `delete [] result_ptr->mask->data;` in `detector.cpp`
=> Fix memleak

docs/en/backends/tensorrt.md, docs/en/benchmark.md, docs/en/index.rst, docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md, docs/zh_cn/benchmark.md
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily to receive feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
Instruction for building mmdeploy on Jetsons and update its benchmark.
- Add link of installing mmdeploy on Jetsons to `docs/en/backends/tensorrt.md`
- Add nano benchmark for mmcls in `docs/en/benchmark.md` and `docs/zh-cn/benchmark.md`
- Add `docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md`
Chinese doc for installing mmdeploy on jetsons need all jetson series updated first.
=> [Doc] Nano benchmark and tutorial

cmake/MMDeployConfig.cmake.in, demo/csrc/CMakeLists.txt
=> [Fix] fix missing deploy_core

docs/en/faq.md, mmdeploy/backend/tensorrt/wrapper.py
This PR add FAQ about TensorRT. And add assert about TensorRT input shapes.
=> [Doc] Update FAQ for TensorRT

docs/en/backends/openvino.md, docs/en/build.md, docs/en/get_started.md, docs/zh_cn/build.md, docs/zh_cn/get_started.md
Fix docs about mmcv-full version about openvino note.
Fix docs about mmcv-full version about openvino note.
en/build.md
en/backend/openvino.md
=> [Docs]: Update doc for openvino installation

mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
Batched nms require a lot of index node to support batch inference, which is not necessary.
Check if the deploy_cfg require static shape and batch size is 1.
Simplify nms.
=> [Enhancement] Simplify non batch nms

docs/en/tutorials/how_to_evaluate_a_model.md, docs/en/tutorials/how_to_measure_performance_of_models.md, mmdeploy/codebase/base/task.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmedit/deploy/super_resolution.py, mmdeploy/codebase/mmocr/deploy/text_detection.py, mmdeploy/codebase/mmocr/deploy/text_recognition.py, mmdeploy/codebase/mmseg/deploy/segmentation.py, mmdeploy/utils/timer.py, tools/test.py
The evaluation results of `test.py` are hard to redirect to a file.
Use logger to manage all the logs of `test.py`. Now all the outputs of `test.py` will be saved to `--log2file`.
=> [Enhacement] Allow test.py to save evaluation results

mmdeploy/codebase/mmcls/deploy/classification_model.py, mmdeploy/codebase/mmocr/deploy/mmocr.py, mmdeploy/codebase/mmocr/deploy/text_detection_model.py, mmdeploy/codebase/mmocr/deploy/text_recognition_model.py
MMOCR embedded `single_gpu_test` to their own repository and fix the bug of failing `--show-dir` after [v0.4.1](https://github.com/open-mmlab/mmocr/pull/755)
=> [Enhancement] Support mmocr v0.4+

mmdeploy/backend/onnxruntime/wrapper.py
```
[                                                  ] 0/104125, elapsed: 0s, ETA:Traceback (most recent call last):
File "/home/PJLAB/maningsheng/projects/openmmlab/mmdeploy/scripts/mmpose/../../tools/test.py", line 140, in <module>
main()
File "/home/PJLAB/maningsheng/projects/openmmlab/mmdeploy/scripts/mmpose/../../tools/test.py", line 133, in main
args.show_dir)
File "/home/PJLAB/maningsheng/projects/openmmlab/mmdeploy/mmdeploy/codebase/base/task.py", line 138, in single_gpu_test
out_dir, **kwargs)
File "/home/PJLAB/maningsheng/projects/openmmlab/mmdeploy/mmdeploy/codebase/mmpose/deploy/mmpose.py", line 132, in single_gpu_test
return single_gpu_test(model, data_loader)
File "/home/PJLAB/maningsheng/projects/openmmlab/mmpose/mmpose/apis/test.py", line 37, in single_gpu_test
result = …
```
=> fix onnxruntime wrapper for gpu inference

requirements/optional.txt
Lock mmcls version to v0.19.0 since v0.20.0 has dependency of mmcv>=v1.4.2. Also see issue https://github.com/open-mmlab/mmdeploy/issues/130
Lock mmcls version
None
=> lock mmcls version

docs/en/tutorials/how_to_support_new_backends.md, mmdeploy/backend/openvino/onnx2openvino.py
Fixed problem #118 with `capture_output` when using Python 3.6.
- `docs/en/tutorials/how_to_support_new_backends.md`: Updated documentation.
- `mmdeploy/backend/openvino/onnx2openvino.py`: Replaced `capture_output` with `stdout=PIPE, stderr=PIPE`.
=> [Enhancement] Fix tests for OpenVINO with Python 3.6

.github/workflows/build.yml, docs/en/build.md, docs/en/get_started.md, docs/zh_cn/build.md, docs/zh_cn/get_started.md
Update mmcv installation as in mmtracking [PR](https://github.com/open-mmlab/mmtracking/pull/409)
Update mmcv installation in CI and documents.
None
=> update mmcv installation

docs/en/benchmark.md, docs/zh_cn/benchmark.md
Note that some models (including mmocr models) are not supported.
=> [Doc] Update Nvidia Jetson TX2 benchmark

docker/GPU/Dockerfile, docs/en/build.md, docs/zh_cn/build.md
To avoid breaking changes which arose from recent updates in pplcv , fix pplcv to v0.6.1
=> Lock pplcv to v0.6.1

docs/en/get_started.md, docs/zh_cn/get_started.md
Fix a small naming inconsistency by renaming **backend_models** to **backend_files**, so that it becomes consistent with the usage of [inference_model](https://github.com/open-mmlab/mmdeploy/blob/26d40fe883c941a668bf7c309b168e4f01a6f6c2/mmdeploy/apis/inference.py#L11).
Change from
```
from mmdeploy.apis import inference_model
result = inference_model(model_cfg, deploy_cfg, backend_models, img=img, device=device)
```
To
```
from mmdeploy.apis import inference_model
result = inference_model(model_cfg, deploy_cfg, backend_files, img=img, device=device)
```
It should be ready to merge.
=> [Docs] Update get_started.md

.pre-commit-config.yaml, demo/demo_rewrite.py, mmdeploy/codebase/mmdet/core/ops/detection_output.py, mmdeploy/codebase/mmdet/core/ops/prior_box.py, mmdeploy/codebase/mmdet/models/backbones.py, mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py, mmdeploy/codebase/mmdet/models/necks.py, tests/test_apis/test_onnx2ncnn.py, tools/onnx2ncnn.py
Add a new pre-commit-hook to automatically add a copyright. …
=> Add a new pre-commit-hook to automatically add a copyright

mmdeploy/pytorch/ops/__init__.py, mmdeploy/pytorch/ops/hardsigmoid.py, tests/test_pytorch/test_pytorch_ops.py
Hardsigmoid export is not supported before torch1.9. This PR adds such support for torch<=1.8.
=> support export hardsigmoid in torch<=1.8

csrc/backend_ops/ncnn/ops/CMakeLists.txt, csrc/backend_ops/ncnn/ops/ncnn_ops_register.h, csrc/backend_ops/ncnn/pyncnn_ext/CMakeLists.txt, csrc/net/ncnn/ncnn_net.cpp, mmdeploy/backend/ncnn/init_plugins.py
ncnn was not taken into consideration in #106, this PR tries to bring it back.
1. Pre-commit or …
=> [Fix] fix ncnn

docs/en/supported_models.md, docs/en/tutorials/how_to_convert_model.md, docs/zh_cn/tutorials/how_to_convert_model.md, mmdeploy/version.py, tools/deploy.py
=> [Docs]: update docs and argument descriptions

mmdeploy/codebase/mmseg/deploy/segmentation.py
fix unnecessary change of config for dynamic exporting #195
Only change preprocess pipeline if input_shape set for static exporting and inference.
None
=> fix unnecessary change of config for dynamic exporting

CMakeLists.txt
Some users forget to set the value of M DEPLOY CODEBASES, so the compiled library will lack the corresponding header file
this pr set the default value of MMDEPLOY_CODEBASES to "all"
If this PR introduces a new feature, it is better to list some use cases here, and …
=> set the default value of MMDEPLOY_CODEBASES to "all"

csrc/backend_ops/tensorrt/common/common_cuda_helper.hpp, csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.cpp, csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.hpp, csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu, csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align_kernel.hpp, mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py, tests/test_ops/test_ops.py
Use `fma` to perform interpolate.
Test input:
```
rois shape: torch.Size([1000, 5])
feat 0 shape: torch.Size([1, 256, 200, 304])
feat 1 shape: torch.Size([1, 256, 100, 152])
feat 2 shape: torch.Size([1, 256, 50, 76])
feat 3 shape: torch.Size([1, 256, 25, 38])
```
Note that there is not much speed up( less than 0.5ms). Since load feat (which is randomly accessed, can not be cached) would cost a lot of time. I have no idea how to perform the optimize.
Or should I add a fp16 implementation?
=> [Enhancement] Optimize multilevel roi align

tests/test_codebase/test_mmdet/test_mmdet_models.py
weight of `L2Norm` has not been initialized. Which might lead to a test failure.
initialize weight.
=> [Fix] fix l2norm test

csrc/preprocess/cpu/CMakeLists.txt, csrc/preprocess/cpu/default_format_bundle_impl.cpp, csrc/preprocess/cuda/CMakeLists.txt, csrc/preprocess/cuda/default_format_bundle_impl.cpp, csrc/preprocess/transform/CMakeLists.txt, csrc/preprocess/transform/collect.h, csrc/preprocess/transform/crop.h, csrc/preprocess/transform/default_format_bundle.cpp, csrc/preprocess/transform/default_format_bundle.h, csrc/preprocess/transform/image2tensor.h, csrc/preprocess/transform/load.h, csrc/preprocess/transform/normalize.h, mmdeploy/utils/export_info.py, tests/test_csrc/preprocess/test_default_format_bundle.cpp
To add DefaultFormatBundle to preprocess for SDK.
**modified**
- csrc/preprocess/cpu/CMakeLists.txt
- csrc/preprocess/cuda/CMakeLists.txt
- mmdeploy/utils/export_info.py: remove the replacement from *DefaultFormatBundle* to *Image2Tensor*
**Added**
- csrc/preprocess/cuda/default_format_bundle_impl.cpp
- csrc/preprocess/cpu/default_format_bundle_impl.cpp
- csrc/preprocess/transform/default_format_bundle.cpp
- csrc/preprocess/transform/default_format_bundle.h
- tests/test_csrc/preprocess/test_default_format_bundle.cpp
I am not sure but I just dismissed `DC` part and label stuff for the **DefaultFormatBundle** in mmdet preprocess. Codes are below:
```python
def __call__(self, results):
"""Call function to transform and format common fields in results.
Args:
results (dict): Result dict …
```
=> Add DefaultFormatBundle

csrc/core/mpl/static_any.h, csrc/core/value.h, tests/test_csrc/core/test_value.cpp
`std::any` is not guaranteed to work on multi-dll or dynamic module loading configuration. Switched to a statically typed version (by specializing `mmdeploy::traits::TypeId<T>`) of `std::any` based on libc++'s implementation.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
=> [Enhancement] Switch to statically typed Value::Any

mmdeploy/apis/pytorch2onnx.py
Use `verbose` instead of `strip_doc_string` for onnx export according to [official docstring](https://pytorch.org/docs/master/onnx.html#functions)
Related issue #268.
=> [Bug] compatible with torch 1.11

csrc/backend_ops/tensorrt/CMakeLists.txt, csrc/device/cuda/CMakeLists.txt, csrc/net/trt/CMakeLists.txt, csrc/preprocess/cuda/CMakeLists.txt
suppress 'CMAKE_CUDA_ARCHITECTURES' empty warning when building trt backend. #269
=> suppress CMAKE_CUDA_ARCHITECTURES warning

csrc/codebase/mmpose/CMakeLists.txt, csrc/codebase/mmpose/mmpose.h, demo/csrc/pose_detection.cpp
fix pose-demo unused variable
fix codebase(mmpose) windows build
#306
=> fix pose demo and windows build

csrc/apis/c/text_recognizer.cpp, demo/csrc/ocr.cpp
Inside `mmdeploy_text_recognizer_apply_bbox`, when `bbox_count` is 0 for an image, inference will be launched with no input supplied.
This PR resolves the problem by skipping inference for images with `bbox_count` equal to zero.
=> fixed a bug causes text-recognizer to fail when (non-NULL) empty bbox list is passed

mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
We can save results when using `tools/test.py`. However, MMEditing fails to do this because we lack some codes.
Copy the codes related to save results from `mmedit.basic_restorer.py`  to `mmdeploy.super_resolution_model.py`
=> [Fix] MMEditing cannot save results when testing

docs/en/build/linux.md, docs/en/faq.md, docs/zh_cn/build/linux.md, mmdeploy/core/rewriters/rewriter_utils.py
* Fix typo
* Upate FAQ for pip install error
* Add description for ncnn LD_LIBRARY_PATH
Single PR is not worth reviewing, so batching.
Update docs and comments.
no BC-breaking.
no need test. …
=> docs(build): fix typo

csrc/net/openvino/openvino_net.cpp
1. the internal openvino not exported in binary and can't be loaded on windows (#340)
=> fix openvino export tmp model, add binary flag

csrc/apis/c/classifier.cpp, csrc/apis/c/detector.cpp, csrc/apis/c/pose_detector.cpp, csrc/apis/c/segmentor.cpp, csrc/apis/c/text_recognizer.cpp
In sdk c api, the input mat type of some codebase always point to the first mat type, which I think is wrong.
=> fix wrong input mat type

configs/mmdet/detection/detection_openvino_dynamic-300x300.py
When using `configs/mmdet/detection/detection_openvino_dynamic-300x300.py` will trigger the error `../_base_/base_openvino_dynamic.py don't exist`.
Fixed mmdet openvino dynamic 300x300 cfg base path.
=> [BUG] Fix mmdet openvino dynamic 300x300 cfg base

docker/GPU/Dockerfile
#344  
Add onnxruntime support in cmake arguments.
=> Fix: add onnxruntime building option in gpu dockerfile

docs/en/backends/ncnn.md, docs/en/build/android.md, docs/en/build/linux.md, docs/zh_cn/build/android.md, docs/zh_cn/build/linux.md
Fix docs problems
NCNN should use 20220216 version to avoid 4D Tensor not supported
`ncnn_DIR` is not equal to 'NCNN_DIR` 
None.
None. …
=> [Docs] fix ncnn docs

cmake/modules/FindTENSORRT.cmake
some user may copy the tensorrt library to cuda dir like /usr/local/cuda, so add ${CUDA_TOOLKIT_ROOT_DIR} as a search path of tensorrt. (#324)
=> add CUDA_TOOKIT_ROOT_DIR as tensorrt detect dir

docs/en/benchmark.md, docs/zh_cn/benchmark.md
=> fix benchmark

mmdeploy/codebase/mmseg/deploy/segmentation.py
=> [Fix] Fix seg name

configs/mmcls/mmcls_regression_test.yaml, configs/mmdet/detection/detection_openvino_dynamic-300x300.py, configs/mmdet/mmdet_regression_test.yaml, configs/mmedit/mmedit_regression_test.yaml, configs/mmocr/mmocr_regression_test.yaml, configs/mmpose/mmpose_regression_test.yaml, configs/mmpose/pose-detection_torchscript.py, configs/mmseg/mmseg_regression_test.yaml, docs/zh_cn/tutorials/how_to_do_regression_test.md, requirements/tests.txt, tools/regression_test.py
I got some rebase problem on my previous PR #271, so I open another one. 😄 
Regression test for mmedploy.
This PR is for mmdeploy regession test.
New doc: `docs/zh_cn/tutorials/how_to_do_regression_test.md`
```shell
python ./tools/regression_test.py \
--deploy-yml "${DEPLOY_YML_PATH}" \
--backends "${BACKEND}" \
--work-dir "${WORK_DIR}" \
--device "${DEVICE}" \
--log-level INFO \
[--performance]
```
- ~~segm~~
- ~~PQ~~
- ~~mmdet3d~~
<div align=center>
</div>
This is all reports after the regrssion finish under `${WORK_DIR}`:
This is a mmocr report example:
=> [Feature] Regression test for mmdeploy

mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py, mmdeploy/codebase/mmdet/deploy/utils.py, mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py, mmdeploy/codebase/mmdet/models/dense_heads/gfl_head.py, mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py, mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py, mmdeploy/codebase/mmdet/models/roi_heads/bbox_head.py, mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py
Expand cost more memory at runtime and some backend does not support it.
Try to remove all expand ops that can be broadcast.
=> [Enhance] remove expand from mmdet rewriter

.github/workflows/build.yml
CUDA ci failed.
Fix ci.
The error is caused by a public key error when `apt-get update`
```bash
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
``` 
which would block all `apt-get install` which include `python-dev`. `setuptools` will not …
=> [Fix] Fix ci

csrc/core/utils/formatter.h
Support latest spdlog, in which implicit conversion from enum classes to int is banned.
resolves #329 …
=> [Fix] support latest spdlog

csrc/backend_ops/ncnn/ops/constantofshape/constantofshape.cpp, csrc/backend_ops/ncnn/ops/expand/expand.cpp
I using `dev-v0.5.0` for base, If I merge to `master` it will be plenty file changed which is not my commit. So I PR to `v0.5.0`.
When I compile project, I met warning for ncnn : `control reaches end of non-void function [-Wreturn-type]`
- Add `return -1` at the end of `Expand::forward` of `csrc/backend_ops/ncnn/ops/expand/expand.cpp`
- Add `return -1` at the end of  `ConstantOfShape::forward` of `csrc/backend_ops/ncnn/ops/constantofshape/constantofshape.cpp`
Also I make the mutex if to `if ... else if ...`
=> [Fix] ncnn [-Wreturn-type] and improve mutex `if`

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Fix mmdet ONNXRuntime cuda test bug.
Some error happended when I test the yolox speed.
```
python tools/test.py \
configs/mmdet/detection/detection_onnxruntime_dynamic.py \
../mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py \
--model work_dir/det/yolox-s-ort-dynamic/end2end.onnx \
--speed-test \
--log2file work_dir/det/yolox-s-ort-dynamic/logs-cuda.txt \
--device cuda:0
```
error
```
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
Under the line …
=> fix mmdet ONNXRuntime cuda test bug

requirements/optional.txt
The requirements of MMPose conflict with OpenVINO.
```
mmpose>=0.24.0,<=0.25.1
``` …
=> [Fix] Limit mmpose requirement

docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md
Improve mmdeploy build on Jetson doc: `docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md`
I follow the doc to build mmdeploy on Jetson nano (4G version, Jetpack 4.6.1), and I add some solution or details when I can't get it from the doc.
=> [Doc] Improve Jetson tutorial install doc

tests/test_codebase/test_mmcls/test_classification.py
```
tests/test_codebase/test_mmcls/test_classification.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <mmdeploy.codebase.mmcls.deploy.classification.Classification object at 0x7f67c80f4150>, model_checkpoint = None
cfg_options = None, kwargs = {}
def init_pytorch_model(self,
model_checkpoint: Optional[str] = None,
cfg_options: Optional[Dict] = None,
**kwargs) -> torch.nn.Module:
"""Initialize torch model.
Args:
model_checkpoint (str): The checkpoint file of torch model,
Default: None.
cfg_options (dict): Optional config key-pair parameters.
Returns:
nn.Module: An initialized torch model generated by OpenMMLab
codebases.
"""
if self.from_mmrazor:
>           from mmrazor.apis import …
```
=> fix import mmrazor error in mmcls test

docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md
- Minor fixes in styling and grammar
- Add support for Jetson Xavier NX (Tested and worked)
- Add hardware recommendation
- Change JetPack installation guide URL from jp5.0 to jp4.6.1
- Add a note to select "Jetson SDK Components" when using NVIDIA SDK Manager
- Change PyTorch wheel save location
- Add more dependencies needed for torchvision installation. Otherwise installation error
- Simplify torchvision git cloning branch
- Add installation times for torchvision, MMCV, versioned-hdf5, ppl.cv, model converter, SDK libraries
- Delete "snap" from cmake removal as "apt-get purge" is enough
- Add a note on which scenarios you need to append cu da path and libraries to PATH and LD_LIBRARY_PATH
- Simplify MMCV git cloning branch
- Delete "skip if you don't need MMDeploy C/C++ Inference SDK", …
=> Update: Optimize document

mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
A typo prevents nms from onnxizing correctly if batch size is static and greater than 1.
=> fix: bbox_nms not onnxizing if batch size > 1

mmdeploy/core/optimizers/function_marker.py
Change separator of marker inputs/outputs from `/` to `.` for better naming style.
=> change seperator of marker

docs/zh_cn/tutorials/chapter_03_pytorch2onnx.md
=> [docs] Fix typo in tutorial

mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py, tests/test_codebase/test_mmseg/test_mmseg_models.py
Unnecessary resize in mmseg encode-decoder head: https://github.com/open-mmlab/mmsegmentation/issues/1529
None
=> fix mmseg twice resize

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
fix https://github.com/open-mmlab/mmdeploy/issues/506
=> Fix mask test with mismatched device

mmdeploy/codebase/mmpose/deploy/pose_detection.py, tests/test_codebase/test_mmpose/data/model.py, tests/test_codebase/test_mmpose/test_pose_detection.py
Fix mmpose error of v0.26.0
None
=> fix: compatable with mmpose v0.26

CMakeLists.txt
fix C# API build option
```
set(MMDEPLOY_BUILD_SDK_CSHARP_API "build MMDeployExtern.dll for C# API" OFF) 
->
option(MMDEPLOY_BUILD_SDK_CSHARP_API "build MMDeployExtern.dll for C# API" OFF)
```
=> fix C# API build option

csrc/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp, csrc/backend_ops/ncnn/onnx2ncnn/fuse_pass.h, csrc/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp, csrc/backend_ops/ncnn/onnx2ncnn/shape_inference.cpp, csrc/backend_ops/ncnn/onnx2ncnn/shape_inference.h, mmdeploy/pytorch/functions/linear.py, mmdeploy/pytorch/ops/__init__.py, mmdeploy/pytorch/ops/linear.py, tests/test_pytorch/test_pytorch_ops.py
Fix  review advices from https://github.com/Tencent/ncnn/pull/3730
* mmdeploy split nn.Linear into multiple opr when input.shape=[1, x, x]
* remove ~100 redundant opr in `end2end.param` (289 --> 195)
* Use `Crop axis=0 starts=0 ends=1` opr instead of  `Gather axis=0 indices=[0]` in ViT.param
* Add linear testcase
* Enable fast GELU by default (from nihui)
If so, please describe how it breaks the compatibility and …
=> improvement(ViT): use Crop to subtitude Gather

cmake/cuda.cmake
For Jetson AGX Orin, we need `-DCMAKE_CUDA_ARCHITECTURES=87` in building the binary, or it will not convert models with NMS to TensorRT correctly (the assertion at [nmsInference](https://github.com/open-mmlab/mmdeploy/blob/v0.5.0/csrc/backend_ops/tensorrt/batched_nms/trt_batched_nms.cpp#L99) fails at inference time, and you can find it is because of the error `no kernel image is available for execution on the device` at [permuteData](https://github.com/open-mmlab/mmdeploy/blob/v0.5.0/csrc/backend_ops/tensorrt/common_impl/nms/batched_nms_kernel.cpp#L77)).
Added `gencode` option and it now supports CC=87 as default.
If your CUDA compiler is >= 11.4, additional binaries are built.
MMDeploy for Jetson AGX Orin
2. …
=> Support compute capability 87 architectures such as Jetson AGX Orin

README_zh-CN.md, mmdeploy/backend/ncnn/init_plugins.py, mmdeploy/mmcv/ops/__init__.py, mmdeploy/mmcv/ops/transformer.py, mmdeploy/utils/utils.py, tests/test_mmcv/test_mmcv_ops.py, tools/deploy.py
* improve patch embed, remove redundant onnx shape opr
* rewrite patch embed
before:
```mermaid
flowchart  TD;
conv-->shape;
shape-->slice;
slice-->concat;
concat-->reshape;
conv-->reshape;
```
after:
```mermaid
flowchart  TD;
conv-->reshape;
```
* if `get_onnx2ncnn_path` failed, give more tips
* fix-typo
If so, please describe how it breaks the compatibility and how the downstream projects should modify their …
=> Improve ncnn patch embed

mmdeploy/codebase/mmocr/deploy/text_recognition_model.py
Text Recognition model visualize failed when mmocr >= 0.5.0 because mmocr 0.5.0 changed the `show_result` api to a static method.
Add conditional statement for mmocr versions to adapt different `show_result` apis.
None.
None.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be …
=> [Fix] adapt mmocr different versions

docs/zh_cn/01-how-to-build/linux-x86_64.md
Modify the document
make -install -> make install
run：
```shell
make -install
```
which return:
```shell
(open-mmlab) xx@xx:~/code/mmdeploy-master/build$ make -install
make: invalid option -- 'a'
Usage: make [options] [target] ...
Options:
-b, -m                      Ignored for compatibility.
-B, --always-make           Unconditionally make all targets.
-C DIRECTORY, --directory=DIRECTORY
Change to DIRECTORY before doing anything.
-d                          Print lots of debugging information.
--debug[=FLAGS]             Print various types of debugging information.
-e, --environment-overrides
Environment variables override makefiles.
--eval=STRING               Evaluate STRING as a makefile statement.
-f FILE, --file=FILE, --makefile=FILE
Read FILE as a makefile.
-h, --help …
```
=> [Document] make -install -> make install

csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Classifier.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Detector.cs, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/TextDetector.cs
to address https://github.com/open-mmlab/mmdeploy/issues/613
Fix wrong args in mmdeploy_detector_release_result
=> [Fix] fix csharp api detector release result

mmdeploy/apis/calibration.py, mmdeploy/apis/onnx/export.py, mmdeploy/apis/torch_jit/trace.py, mmdeploy/codebase/mmcls/models/backbones/__init__.py, mmdeploy/codebase/mmcls/models/backbones/shufflenet_v2.py, mmdeploy/utils/config_utils.py
=> fix shufflenetv2 with trt

docs/en/01-how-to-build/linux-x86_64.md
If there is a variable in the string, single quotes will ignored it, while double quotes will bring the variable into the string after parsing
如果字符串中有变量，单引号会忽略，而双引号会把变量解析以后带入字符串
Change the document.
If one excute:
```shell
echo 'export LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH' >> ~/.bashrc
```
In the last line of `~/.bashrc`, that will be `export LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH`.
$ONNXRUNTIME_DIR and $LD_LIBRARY_PATH will not be parsed.
=> [Document] ' -> "

csrc/mmdeploy/backend_ops/tensorrt/common/trt_plugin_base.hpp, csrc/mmdeploy/backend_ops/tensorrt/grid_priors/trt_grid_priors.cpp, csrc/mmdeploy/backend_ops/tensorrt/grid_priors/trt_grid_priors.hpp, csrc/mmdeploy/backend_ops/tensorrt/grid_priors/trt_grid_priors_kernel.cu, csrc/mmdeploy/backend_ops/tensorrt/grid_priors/trt_grid_priors_kernel.hpp, docs/en/ops/tensorrt.md, mmdeploy/codebase/mmdet/core/__init__.py, mmdeploy/codebase/mmdet/core/anchor.py, tests/test_codebase/test_mmdet/test_mmdet_core.py, tests/test_ops/test_ops.py, tests/test_ops/utils.py
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Memcpy DtoD (Device -> Device)         0.00%       0.000us         0.00%       0.000us       0.000us      73.000us        47.10%      73.000us      73.000us             1  
void cuFillLayer::fill<int>(cuFillLayer::KernelArgs<...         0.00% …
```
=> [Enhancement] TensorRT Anchor generator plugin

mmdeploy/backend/tensorrt/init_plugins.py
This will fixed: plugin not found issue in windows caused by: https://github.com/open-mmlab/mmdeploy/commit/4710ab910d44103146a80794d739eafeac5b2cba
Added previous candidate paths to the latest candidate path
```python
candidates = [
'../../lib/libmmdeploy_tensorrt_ops.so', 
'../../lib/mmdeploy_tensorrt_ops.dll', 
'../../../build/lib/libmmdeploy_tensorrt_ops.so', …
```
=> Fixed tensorrt plugin not found in Windows

mmdeploy/codebase/mmpose/deploy/pose_detection.py
When export mmpose model with --dump-info, if deploy_cfg doesn't contains input_shape, we should consider data_cfg['image_size'] in model config.
=> [FIX] fix dump info of mmpose if input_shape is not given in deploy_cfg

mmdeploy/apis/pytorch2onnx.py, mmdeploy/codebase/mmcls/models/classifiers/base.py, mmdeploy/codebase/mmdet/models/detectors/base.py, mmdeploy/codebase/mmseg/models/segmentors/base.py, tests/test_codebase/test_mmcls/test_mmcls_models.py, tools/onnx2ncnn.py, tools/onnx2pplnn.py, tools/onnx2tensorrt.py
=> pass img_metas while exporting to onnx

csrc/mmdeploy/apis/java/native/CMakeLists.txt, docs/en/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/android.md
Users build failed on android cross compilation for building Java APIs.
Update android cross compilation tutorial for Java API feature.
Fix CMakeLists for build on android.
None.
None. …
=> [Fix] Fix android build

mmdeploy/apis/core/pipeline_manager.py, mmdeploy/backend/pplnn/utils.py
fix wrong exit code in pipeline_manager. Tools like regression_test.py need a nonzero exit code if the program exits wrongly.
Set exit code to -1 in pipeline_manager
None
=> fix wrong exit code in pipeline_manager

mmdeploy/apis/calibration.py, mmdeploy/core/rewriters/rewriter_manager.py
Fix passing wrong type for argument `backend` in `mmdeploy/apis/calibration.py`.
Related issue:https://github.com/open-mmlab/mmdeploy/issues/709
Convert to `backend` to `str`  type/ 
Nonw
=> fix passing wrong backend type for patch_model

.github/scripts/test_onnx2ncnn.py, .github/workflows/backend-ncnn.yml, .gitignore, csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/CMakeLists.txt, docs/en/06-developer-guide/partition_model.md, docs/zh_cn/04-developer-guide/partition_model.md, docs/zh_cn/04-developer-guide/support_new_backend.md, mmdeploy/backend/ncnn/init_plugins.py, tools/deploy.py, tools/onnx2ncnn.py, tools/package_tools/mmdeploy_builder.py
fix name confict with `tencent/ncnn/onnx2ncnn`.
* rename target to `mmdeploy_onnx2ncnn`
* improve `get_onnx2ncnn_path`
* improve `find_package(protobuf)`,  `FindProtobuf.cmake` may fails to find `protoc`
* update docs
old version using `onnx2ncnn` while new version works with `mmdeploy_onnx2ncnn`
2. The modification is covered by …
=> Rename onnx2ncnn to mmdeploy_onnx2ncnn

mmdeploy/codebase/mmdet/core/bbox/__init__.py, mmdeploy/codebase/mmdet/core/bbox/distance_point_bbox_coder.py, mmdeploy/codebase/mmdet/core/bbox/transforms.py, mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py, tests/test_codebase/test_mmdet/test_mmdet_core.py
Fix bugs mentioned in #679 
base_dense_head.py
None.
None.
=> [Fix] Fix mmdet ort static shape bug.

docs/en/conf.py, docs/en/get_started.md, docs/zh_cn/02-how-to-run/quantize_model.md, docs/zh_cn/conf.py, docs/zh_cn/get_started.md, requirements/docs.txt, requirements/readthedocs.txt
1. C++ code block is not highlighted in readthedocs
2. mermaid graph in markdown is not rendered correctly in readthedocs
1. `get_started.md`, `conf.py` both in en / cn folder
2. quantize_model.md
3. add `sphinxcontrib-mermaid` in docs.txt as well as readthedocs.txt
If …
=> Fix get-started rendering issues in readthedocs

requirements/docs.txt
https://readthedocs.org/projects/mmcv/builds/17455215/
Failed to build docs due to breaking changes of markdown3.4. More details at https://github.com/ryanfox/sphinx-markdown-tables/issues/36.
Set `markdown<3.4.0`. Refer to https://github.com/open-mmlab/mmcv/pull/2121/files
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
=> Fix markdown table rendering failure in readthedocs

mmdeploy/apis/onnx/optimizer.py, mmdeploy/core/rewriters/rewriter_utils.py
1. PyTorch will inspect the rewritten symbolic function(which has been replaced with a ContextCaller)
https://github.com/pytorch/pytorch/blob/67ece03c8cd632cce9523cd96efde6f2d1cc8121/torch/onnx/utils.py#L1333
2. PyTorch add a new pass `_jit_pass_onnx_deduplicate_initializers`, which will turn `k` in `topk` from `initializer` to `Identity`. Which broken the TensorRT export.
https://github.com/pytorch/pytorch/blob/67ece03c8cd632cce9523cd96efde6f2d1cc8121/torch/onnx/utils.py#L1101
=> [Fix][P0] Fix for torch1.12

tools/check_env.py
Use `is_custom_ops_available` instead of `is_available` for check_env.py.
=> [Fix] fix check env

csrc/mmdeploy/backend_ops/torchscript/optimizer/ir/subgraph_matcher.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/flatten_cls_head.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/fuse_select_assign.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.cpp
long has different sizes in different environments.
Replace `long` with `int64_t`
Not sure if I have replaced all of them. …
=> [Fix] Fix setup on non-linux-x64

docs/en/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/android.md
update document for building android sdk.
=> update document for building android sdk

.github/workflows/build.yml, CMakeLists.txt, csrc/mmdeploy/preprocess/transform/collect.cpp, tests/test_csrc/core/test_execution.cpp, tests/test_csrc/preprocess/test_resize.cpp, tests/test_csrc/test_resource.h
Improve codecov
* Add `MMDEPLOY_COVERAGE` build option
* CI build SDK and run unit test, send report to codecov
* Fix `test_resize` because of round policy
4. The …
=> improvement(sdk): add sdk code coverage

mmdeploy/codebase/mmcls/deploy/classification_model.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmedit/deploy/super_resolution_model.py, mmdeploy/codebase/mmocr/deploy/text_detection_model.py, mmdeploy/codebase/mmocr/deploy/text_recognition_model.py, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py, mmdeploy/codebase/mmrotate/deploy/rotated_detection_model.py, mmdeploy/codebase/mmseg/deploy/segmentation_model.py
Fix sdk backend when use tools/test.py after python api chaned(#794)
=> [Fix] fix sdk backend when use tools/test.py 

docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/faq.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/faq.md
add document for prebuit package usage on windows.
=> add prebuild package usage docs on windows

CMakeLists.txt, docker/CPU/Dockerfile, docker/GPU/Dockerfile, docs/en/01-how-to-build/android.md, docs/en/01-how-to-build/jetsons.md, docs/en/01-how-to-build/linux-x86_64.md, docs/en/01-how-to-build/windows.md, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/01-how-to-build/android.md, docs/zh_cn/01-how-to-build/jetsons.md, docs/zh_cn/01-how-to-build/linux-x86_64.md, docs/zh_cn/01-how-to-build/windows.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, requirements/docs.txt, tools/package_tools/packaging/mmdeploy_python/version.py
Refactor get_started documents according to internal reviews
en/get_started.md
zh_cn/get_started.md
1. Pre-commit or other linting tools are used to fix the …
=> [Enhancement] Improve get_started documents and bump version to 0.7.0

docs/zh_cn/02-how-to-run/quantize_model.md, tools/deploy.py
When I try to follow the docs to quantize model, I find some error. So this pr is to solve these errors.
1.exchange MODEL_PATH and MODEL_CONFIG in docs/zh_cn/02-how-to-run/quantize_model.md
2.add args.device in backend ncnn, thus make sure that this parameter is passed to function get_table()
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
=> fix error when set device cpu && fix docs error

docs/en/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
Fix doc error of building C examples.
To fix wrong path description in docs which incurs the failure of building C examples.
Modify the doc description of [`02-how-to-run/prebuilt_package_windows.md`](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/02-how-to-run/prebuilt_package_windows.md) and its [english version](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/02-how-to-run/prebuilt_package_windows.md).
Modify `cmake ..` into `cmake ..\cpp` for the directory `..` hasn't `CMakeLists.txt` which can cause a failure of compilation.
=> Fix doc error of building C examples

mmdeploy/codebase/base/task.py, mmdeploy/codebase/mmdet/deploy/mmdetection.py, tools/test.py
1. fix https://github.com/open-mmlab/mmdeploy/issues/905
2. Some small images are filtered out for coco dataset when `cfg.data.test.test_mode` is `False` which is not aligned with mmdet setting.
1. Set default of `is_sort_dataset` to  `False` to fix https://github.com/open-mmlab/mmdeploy/issues/905
3. set `cfg.data.test.test_mode = True` to align with mmdet [tools](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/tools/test.py#L192) and won't filter small image of the dataset according to [here](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/custom.py#L48).
4. 
None
=> set test_mode for mmdet

docs/en/04-supported-codebases/mmdet3d.md, docs/zh_cn/04-supported-codebases/mmdet3d.md
mmdet3d doc give specified model path
update doc 
=> docs(mmdet3d): give detail model path

.github/workflows/build.yml, .github/workflows/quantize.yml
Fix cuda ci with building `lanms-neo` which is the dependency if `mmocr`.
This problem is also mentioned in the [issue](https://github.com/actions/setup-python/issues/489) of setup-python repo.
Add cflags explicitly in cuda ci:
```
CFLAGS=`python -c 'import sysconfig;print("-I"+sysconfig.get_paths()["include"])'` python -m pip install -r requirements.txt
```
None
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported …
=> fix cuda ci of building lanms-neo

mmdeploy/pytorch/functions/tensor_setitem.py, tests/test_pytorch/test_pytorch_functions.py
slice put would be failed when the value is scalar or single element tensor.
create a tensor when element is scalar …
=> [Bug] fix setitem with scalar or single element tensor

mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py, mmdeploy/core/rewriters/function_rewriter.py, tests/test_core/test_function_rewriter.py
test script:
```python
import torch
from torch import matmul
try:
from mmdeploy.core import FUNCTION_REWRITER, RewriterContext
except Exception:
pass
@FUNCTION_REWRITER.register_rewriter('torch.matmul')
def matmul__custom(ctx, input, other):
print('Rewriter enabled')
return ctx.origin_func(input, other)
print('xxx before')
with RewriterContext():
x = torch.rand(4, 4)
y = torch.rand(4, 4)
matmul(x, y)
print('xxx after')
matmul(x, y)
```
=> [Enhancement] Rewriter support pre-import function

mmdeploy/apis/pytorch2onnx.py
ONNX Optimizer(#690) will merge duplicate Initializers and Constant Nodes, but the merged initializers still exists in onnx graph nodes. 
So the count of ncnn blobs has wrong.
`blob_count = blob_names.size - zero_reference_weight_node_count + splitncnn_blob_count`
The merged initializers will minus merged initializers duplicately.
Force close ncnn optimizer for ncnn.
None. …
=> [Fix] Close onnx optimizer for ncnn

tools/package_tools/mmdeploy_builder.py
On windows, there is a Release folder in mmdeploy-xxx.whl. This pr remove this folder.
=> remove Release dir in mmdeploy package

.github/scripts/test_mmcls_full_pipeline.sh
=> fix(CI): ort test all pipeline

tests/regression/mmcls.yml, tests/regression/mmdet.yml, tests/regression/mmedit.yml, tests/regression/mmocr.yml, tests/regression/mmrotate.yml, tests/test_codebase/test_mmcls/test_classification.py, tests/test_codebase/test_mmcls/test_classification_model.py, tests/test_codebase/test_mmcls/test_mmcls_models.py, tests/test_codebase/test_mmdet/test_mmdet_core.py, tests/test_codebase/test_mmdet/test_mmdet_models.py, tests/test_codebase/test_mmdet/test_mmdet_utils.py, tests/test_codebase/test_mmdet/test_object_detection.py, tests/test_codebase/test_mmdet/test_object_detection_model.py, tests/test_codebase/test_mmedit/test_mmedit_models.py, tests/test_codebase/test_mmedit/test_super_resolution.py, tests/test_codebase/test_mmedit/test_super_resolution_model.py, tests/test_codebase/test_mmocr/test_mmocr_models.py, tests/test_codebase/test_mmocr/test_text_detection.py, tests/test_codebase/test_mmocr/test_text_detection_models.py, tests/test_codebase/test_mmocr/test_text_recognition.py, tests/test_codebase/test_mmocr/test_text_recognition_models.py, tests/test_codebase/test_mmseg/test_mmseg_models.py, tests/test_codebase/test_mmseg/test_segmentation.py, tests/test_codebase/test_mmseg/test_segmentation_model.py
1. skipt tests for uninstalled codebases
2. do not run test.py for ort backend in regression config
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
=> Fix: skip tests for uninstalled codebases

docs/en/02-how-to-run/useful_tools.md, docs/zh_cn/02-how-to-run/useful_tools.md, tests/regression/mmdet.yml, tests/regression/mmdet3d.yml, tests/regression/mmrotate.yml, tests/test_codebase/test_mmdet/test_mmdet_utils.py, tests/test_codebase/test_mmdet/test_object_detection_model.py
something missing from https://github.com/open-mmlab/mmdeploy/pull/987
3. If the modification has a dependency on downstream projects of a newer version, this PR should be …
=> fix mmdet ut

csrc/mmdeploy/net/torchscript/CMakeLists.txt, docs/en/05-supported-backends/torchscript.md, docs/zh_cn/05-supported-backends/torchscript.md
Add isolated option for TorchScript SDK backend since it's causing ABI issues hard to resolve.
=> [Fix] Add isolated option for TorchScript SDK backend

requirements/tests.txt, tools/package_tools/mmdeploy_builder.py
The last PR forget to use `osp.join` and `_remove_if_exist` should call after `_call_command`
Fix https://github.com/open-mmlab/mmdeploy/pull/960
=> fix mmdeploy builder on windows

mmdeploy/backend/coreml/ops.py, mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py, mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
https://github.com/open-mmlab/mmdeploy/issues/1038
Two stage detector support is missing.
Please review and merge this PR ASAP. …
=> [BUG P0] Fix CoreML Two Stage detector

docs/zh_cn/tutorial/07_write_a_plugin.md
=> [Doc] update api in doc

docs/en/01-how-to-build/build_from_script.md, docs/zh_cn/01-how-to-build/build_from_script.md, tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/build_ubuntu_x64_ort.py, tools/scripts/build_ubuntu_x64_pplnn.py, tools/scripts/build_ubuntu_x64_torchscript.py
mmdeploy user not check installation successful.  
* update doc
* script add `python3 tools/check_env.py`
4. The documentation has been modified accordingly, like …
=> docs(scripts): update auto install desc

mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
The CoreML backend would produce an error when exporting a model that uses the `RoIAlignFunction`, see issue #1028. This was already fixed in #724, but only for the TorchScript backend specifically.
Since the CoreML backend uses the TorchScript backend as a first step, the condition in https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py has to be updated to support the CoreML backend.
=> Fix `RoIAlignFunction` error for CoreML backend

docs/en/get_started.md, docs/zh_cn/get_started.md
I stumbled upon this typo when following the installation instructions for the TensorRT runtime. It cost me a few minutes until I've noticed that the error that I was receiving (basically "File not found") was caused by a typo in the tar command. I want to save others this time.
The filename in the tar command was changed to reflect the same filename that is downloaded before. More specific, I removed "v" which is not present in the command before.
=> Fixed typo for install commands for TensorRT runtime

csrc/mmdeploy/backend_ops/tensorrt/gather_topk/gather_topk.cpp, csrc/mmdeploy/backend_ops/tensorrt/gather_topk/gather_topk.hpp, csrc/mmdeploy/backend_ops/tensorrt/gather_topk/gather_topk_kernel.cu, csrc/mmdeploy/backend_ops/tensorrt/gather_topk/gather_topk_kernel.hpp, docs/en/06-custom-ops/tensorrt.md, docs/zh_cn/06-custom-ops/tensorrt.md, mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py, mmdeploy/codebase/mmdet/deploy/utils.py, mmdeploy/codebase/mmdet/models/dense_heads/gfl_head.py, mmdeploy/codebase/mmdet/models/dense_heads/reppoints_head.py, mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py, tests/test_ops/test_ops.py
Might be disabled after NVIDIA provide a fix.
The dynamic batch detector failed because https://github.com/NVIDIA/TensorRT/issues/2299.
Add custom ops for gather topk.
old:
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls …
```
=> [CustomOps] TensorRT Gather Topk Ops

mmdeploy/backend/onnxruntime/wrapper.py
When use onnxruntime-gpu, it seems we need to synchronize stream before run session.
=> fix ort-gpu inference

mmdeploy/codebase/mmrotate/deploy/rotated_detection.py, mmdeploy/codebase/mmrotate/models/dense_heads/rotated_anchor_head.py
https://github.com/open-mmlab/mmdeploy/issues/1048
- Fix `get_tensor_from_input`.
- Better head rewriter.
Note that **DO NOT** enable fp16 if you want to use int8 mode.
Test with config:
```python
onnx_config = dict(
type='onnx',
export_params=True,
keep_initializers_as_inputs=False,
opset_version=11,
save_file='end2end.onnx',
input_names=['input'],
output_names=['dets', 'labels'],
input_shape=None,
optimize=True,
dynamic_axes=dict(
input=dict({
0: 'batch',
2: 'height',
3: 'width'
}),
dets=dict({
0: 'batch',
1: 'num_dets' …
```
=> [Fix] fix mmrotate TensorRT int8

mmdeploy/backend/sdk/export_info.py, mmdeploy/codebase/base/task.py, mmdeploy/codebase/mmcls/deploy/classification.py, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py, mmdeploy/codebase/mmedit/deploy/super_resolution.py, mmdeploy/codebase/mmocr/deploy/text_detection.py, mmdeploy/codebase/mmocr/deploy/text_recognition.py, mmdeploy/codebase/mmpose/deploy/pose_detection.py, mmdeploy/codebase/mmrotate/deploy/rotated_detection.py, mmdeploy/codebase/mmseg/deploy/segmentation.py, mmdeploy/utils/__init__.py, mmdeploy/utils/config_utils.py
Based on PR `SDK ocr 2.0` #1006. 
Mainly changed:
1. move get_preprocess into task_processor
2. move get_postprocess into task_processor
3. refactor func `get_models`
=> [2.0] Refactor dump info

mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmrotate/deploy/rotated_detection.py
static shape config failed when pad mode is size instead of size_divisor
`configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco.py`
```python
onnx_config = dict(
type='onnx',
export_params=True,
keep_initializers_as_inputs=False,
opset_version=11,
save_file='end2end.onnx',
input_names=['input'],
output_names=['dets', 'labels'],
input_shape=(896, 896),
optimize=True)
codebase_config = dict(
type='mmdet',
task='ObjectDetection',
model_type='end2end',
post_processing=dict(
score_threshold=0.05, …
```
=> [Fix] fix det with static shape

docs/en/get_started.md
`prebuild` is an incorrect spelling.
`prebuild` to `prebuilt`.
=> Fix typo in get_started.md

.github/workflows/rust_api.yml
The current test commands are highly dependent on the structure of  `mmdeploy-converted-models` and examples of `rust-mmdeploy`. I write a test script in `rust-mmdeploy`, so that the CI test in `mmdeploy` can decouple with the other two repos. Besides, this decouple made the further development of `rust-mmdeploy` more scalable.
Update `rust_api.yml` in `.github/workflows`. Replace running test commands with running a test scripts.
=> Improve CI test of rust-mmdeploy

csrc/mmdeploy/apis/c/mmdeploy/common.cpp, csrc/mmdeploy/apis/c/mmdeploy/common.h, csrc/mmdeploy/apis/c/mmdeploy/common_internal.h, csrc/mmdeploy/apis/c/mmdeploy/pose_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.cpp, csrc/mmdeploy/apis/cxx/mmdeploy/common.hpp, csrc/mmdeploy/utils/opencv/opencv_utils.cpp, csrc/mmdeploy/utils/opencv/opencv_utils.h
Add a device field for `mmdeployt_mat_t` so that it can be filled with data in external device memory.
This breaks ABI compatibility with previous versions. All dependent sources must be recompiled & linked.
=> [Enhancement] Add a device field for `mmdeploy_mat_t`

mmdeploy/pytorch/ops/layer_norm.py
`torch.onnx.symbolic_helper._operator_export_type` api has removed in torch1.12.0
Remove related code
None.
None.
4. The documentation has been modified accordingly, like …
=> [Fix] fix layer norm when torch>=1.12

.github/workflows/rust_api.yml
The current rust_api CI is compiling the latest mmdeploy, and then rust-mmdeploy will link their libraries. But the minor changes in nightly mmdeploy maybe also need to modify Rust code in rust-mmdeploy to pass the CI test which is difficult to manage the main mmdeploy project.
So that this PR will update rust_api CI to just download released pre-built package of mmdeploy rather than compiling the nightly mmdeploy.
Update rust_api CI.
=> Fix rust_api CI

mmdeploy/backend/tensorrt/utils.py
TensorRT 8.4 has mark `max_workspace_size` as deprecated.
1. Use `config.set_memory_pool_limit` instead of `max_workspace_size`.
2. Add check and warning for fp16 and int8. …
=> [Enhancement] Update API for TensorRT8.4

csrc/mmdeploy/apis/c/mmdeploy/detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp, csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp, csrc/mmdeploy/core/mpl/structure.h
Add a tuple-like class that can recover the structure of itself using a pointer to anyone of its elements. And use it to avoid copying when returning dense arrays in C API.
=> [Enhancement] Avoid copying dense arrays in C API

mmdeploy/codebase/base/task.py
Checkpoint loading error when 'device=cpu'.
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
=> checkpoint load RuntimeError

csrc/mmdeploy/backend_ops/tensorrt/scatternd/trt_scatternd_kernel.cu
The ops in tensorrt plugin should use asynchronous CUDA calls with a specified stream.
set stream argument when using async memcpy
=> [FIX] set stream argument when using async memcpy

csrc/mmdeploy/codebase/mmcls/linear_cls.cpp
when `topk` is greater than `class_num`. Appeared in customized datasets.
=> [Fix] fix cls head in SDK

demo/csrc/c/det_pose.cpp
=> [Fix] Fix det_pose demo

csrc/mmdeploy/codebase/mmdet/yolo_head.cpp, csrc/mmdeploy/codebase/mmdet/yolo_head.h, csrc/mmdeploy/experimental/module_adapter.h
Relax module adpater template constraints so that derived class does not have to forward `operator()` to base class.
=> [Fix] Relax module adapter template constraints

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp, csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.h, csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
In torch 1.12, some constant initializer which uses in multiple places will generate `Identity` ops in onnx, which will failed in ncnn.
So we fix the fuse pass in the onnx2ncnn to remove these `Identity` nodes.
Fuse_pass.cpp and onnx2ncnn.cpp
None.
In torch1.12 ncnn deployment which failed before. A typical example are models which have some `Resize` ops which reuse `scale` initializers.
2. The modification is covered by complete unit tests. …
=> [Fix] fix ncnn torch 1.12 master

mmdeploy/codebase/base/mmcodebase.py, mmdeploy/codebase/base/task.py
#1450 changes scope will lead mmyolo scope switch failed
Recover the scope before #1450 for mmyolo and mmdet.
None.
Uses in mmyolo. …
=> [Fix] recover scope mechanism for mmyolo

csrc/mmdeploy/codebase/mmaction/cpu/format_shape_impl.cpp, csrc/mmdeploy/codebase/mmaction/cuda/CMakeLists.txt, csrc/mmdeploy/codebase/mmaction/cuda/format_shape_impl.cpp, csrc/mmdeploy/codebase/mmaction/cuda/transpose.cu, csrc/mmdeploy/codebase/mmaction/format_shape.cpp, csrc/mmdeploy/codebase/mmaction/format_shape.h, csrc/mmdeploy/preprocess/transform/lift.cpp
1. remove cudnn deps for mmaction2::format_shape
2. fix [FormatShape](csrc/mmdeploy/codebase/mmaction/format_shape.cpp), it accept a list but return an object.
3. FormatShape forget to init op.
=> [Fix] Remove cudnn dependency for transform 'mmaction2::format_shape'

csrc/mmdeploy/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.cpp
Fixes: #1537 
Adding `nbInputs` to the `mFeatmapStrides.begin()` iterator cases it to go out of range of the `mFeatmapStrides` vector. When this is compiled in debug build in MS compiler, it causes an exception. If we decrement the value first and then add it to iterator, than the iterator stays in correct vector range.
=>  Fix 'cannot seek vector iterator' in debug windows build

csrc/mmdeploy/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.cpp
Fixes: https://github.com/open-mmlab/mmdeploy/issues/1537
Adding nbInputs to the mFeatmapStrides.begin() iterator causes it to go out of range of the mFeatmapStrides vector. When this is compiled in debug build in MS compiler, it causes an exception. If we decrement the value first and then add it to iterator, than the iterator stays in correct vector range.
4. The documentation has been modified accordingly, like docstring or example …
=> Fix 'cannot seek vector iterator' in debug windows build

csrc/mmdeploy/backend_ops/tensorrt/roi_align/trt_roi_align.cpp, mmdeploy/backend/tensorrt/utils.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, mmdeploy/codebase/mmdet/models/backbones.py, mmdeploy/core/rewriters/rewriter_utils.py, mmdeploy/mmcv/ops/nms.py, mmdeploy/utils/test.py, tests/test_codebase/test_mmdet/test_mmdet_models.py, tests/test_codebase/test_mmdet3d/test_voxel_detection_model.py, tests/test_codebase/test_mmpose/test_mmpose_models.py, tests/test_core/test_function_rewriter.py, tests/test_core/test_module_rewriter.py, tests/test_ops/test_ops.py
Fix unit test.
- string cmp in `trt_roi_align.cpp`
- TensorRT 8.5 api update
- `test_core` bad rewriter error.
- `nms.py` wrong rewriter
- remove unsed test.
- det3d models test recovery error.
- suppress deprecate warning and user warning.
If this PR introduces a new …
=> [Fix] fix unittest and suppress warning

mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Make inference possible with partition model as well as End2EndModel.
Fixed predict function name of PartitionSingleStageModel and PartitionTwoStageModel from forward_test to predict.
Nothing.
Adding no feature.
- This function does not depend on other projects.
- Document of prediction functions are same as other models.
=> [bugfix] rename forward_test to predict

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
Fix some of onnx2ncnn.cpp bugs. Especially for `RTMPose` model deployment later.
-[x] Fix `Gemm` for opset > 9, which is optional for the third input, while original onnx2ncnn needs the third input strictly.
-[x] Sync the `Reduction` op from the newest onnx2ncnn in [ncnn](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp) 
Other ops sync from the newest onnx2ncnn in [ncnn](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp) 
will be fixed later in another PR. This PR is mainly for …
=> [Fix] Fix onnx2ncnn.cpp bugs.

csrc/mmdeploy/codebase/mmaction/cuda/transpose.cu
=> [Fix] Fix build error on cuda10.2 platform

csrc/mmdeploy/operation/cuda/warp_affine.cpp
add missing header <array> for [csrc/mmdeploy/operation/cuda/warp_affine.cpp](https://github.com/open-mmlab/mmdeploy/compare/master...irexyc:fix-windows-build?expand=1#diff-976c675cae3438c27cc3bcfeec3cc8918f711019901227a4686e2e7cee39b125)
=> [Fix] Fix build error on windows-cuda platform

mmdeploy/pytorch/functions/topk.py
#1586 
Same as #1439 
None.
Same as #1439 
=> Cherry-pick #1439 to fix 'topk' on different devices for onnxruntime-gpu inference

docker/CPU/Dockerfile, docker/GPU/Dockerfile, docs/en/01-how-to-build/linux-x86_64.md, docs/en/01-how-to-build/macos-arm64.md, docs/en/get_started.md, docs/zh_cn/01-how-to-build/linux-x86_64.md, docs/zh_cn/01-how-to-build/macos-arm64.md, docs/zh_cn/get_started.md
Switch from `pip install` to `mim install` in several documents and Dockerfiles
```
docker/CPU/Dockerfile
docker/GPU/Dockerfile
docs/en/01-how-to-build/linux-x86_64.md
docs/en/01-how-to-build/macos-arm64.md
docs/en/get_started.md
docs/zh_cn/01-how-to-build/linux-x86_64.md
docs/zh_cn/01-how-to-build/macos-arm64.md
docs/zh_cn/get_started.md
```
2. The …
=> [Update] Switch pip to mim in Docs and Dockerfile

csrc/mmdeploy/device/cpu/cpu_device.cpp
Use `posix_memalign` on Android platform, and set minimum alignment to `sizeof(void*)`
- `std::aligned_alloc` is not available in all versions of NDK toolchains.
- Allocation APIs may fail if `alignment` is too small.
- `new` and `malloc` are aligned to `sizeof(void*)` anyway.
https://en.cppreference.com/w/cpp/memory/c/aligned_alloc
=> [Fix] Fix aligned allocations on Android

docker/CPU/Dockerfile, docker/GPU/Dockerfile
When building the Docker image following the official instructions
```
docker build docker/CPU/ -t mmdeploy:master-cpu
```
it fails to run /root/minicnoda.sh with the following errors
```
Downloading and Extracting Packages
Downloading and Extracting Packages
Preparing transaction: ...working... done
Executing transaction: ...working... done
/root/miniconda.sh: 438: /root/miniconda.sh: [[: not found
Installing * environment...
/root/miniconda.sh: 444: /root/miniconda.sh: [[: not found
```
This PR fixes it by calling the script explicitly with bash.
=> Fixed miniconda.sh errors in Dockerfile

mmdeploy/codebase/mmpose/deploy/pose_detection.py
All other codebases can substitute SyncBN with BN in `build_pytorch_model` function from the `BaseTask` class, while mmpose overwrites the `build_pytorch_model` function without substitute SyncBN with BN. It will failed on RTMPose deployment. 
Call the mmengine API `revert_sync_batchnorm` in mmpose `build_pytorch_model` function.
None.
RTMPose deployment.
2. The modification is covered by complete unit tests. If not, please add more unit tests …
=> [Fix] Substitute SyncBN with BN for mmpose

CMakeLists.txt, csrc/mmdeploy/apis/csharp/MMDeploy.sln, csrc/mmdeploy/apis/csharp/MMDeploy/APIs/common.cs, csrc/mmdeploy/apis/csharp/MMDeploy/MMDeployCSharp.csproj, csrc/mmdeploy/apis/csharp/MMDeploy/MMDeployCSharp.props, csrc/mmdeploy/apis/csharp/README.md, csrc/mmdeploy/codebase/mmdet/yolo_head.cpp, csrc/mmdeploy/codebase/mmdet/yolo_head.h, csrc/mmdeploy/core/CMakeLists.txt, csrc/mmdeploy/device/cpu/cpu_device.cpp, csrc/mmdeploy/experimental/module_adapter.h, csrc/mmdeploy/operation/cuda/warp_affine.cpp, demo/csharp/image_classification/FormDemo.cs, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/Program.cs, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/Program.cs, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/Program.cs, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/Program.cs, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/Program.cs, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/Program.cs, demo/csharp/pose_detection/pose_detection.csproj, demo/csrc/cpp/pose_tracker.cpp
sync pr 1366, 1370, 1460, 1577, 1598, 1601, 1612, 1626
=> Cherry-pick PR  1366, 1370, 1460, 1577, 1598, 1601, 1612, 1626 to dev-1.x 

mmdeploy/codebase/mmcls/deploy/classification.py
The dev-1.x branch failed when deploying mmcls models using CIFAR dataset, because the test_pipeline of CIFAR dataset can not be handled in this branch.
Fix preprocess_model_config for CIFAR dataset.
None.
```
python3 ./tools/deploy.py \
/root/workspace/external_data/code/mmdeploy/configs/mmcls/classification_tensorrt_dynamic-32x32-32x32.py \
/root/workspace/external_data/code/mmclassification/configs/resnet/resnet18_8xb16_cifar10.py \
"/root/workspace/external_data/code/mmdeploy_checkpoints/mmcls/resnetcifar/resnet18_b16x …
```
=> [Fix] Fix preprocess_model_config for CIFAR dataset

configs/mmcls/classification_coreml_static-384x384.py, configs/mmdet/detection/detection_coreml_static-608x608.py, configs/mmocr/text-recognition/text-recognition_coreml_dynamic-32x32-32x640.py, mmdeploy/backend/coreml/backend_manager.py, mmdeploy/backend/coreml/torchscript2coreml.py, mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py, mmdeploy/pytorch/functions/topk.py, tests/test_backend/test_wrapper.py
=> Fix coreml

csrc/mmdeploy/operation/cuda/cvtcolor.cpp, csrc/mmdeploy/preprocess/transform/load.cpp
Fix several bugs in the preprocessing of single channel images.
=> [Fix] Fix several bugs in the preprocessing of single channel images

tools/scripts/build_ubuntu_x64_ncnn.py, tools/scripts/build_ubuntu_x64_ort.py, tools/scripts/build_ubuntu_x64_tvm.py
script install ncnn failed on the docker image `mmdeploy-ci-ubuntu-20.04-cu113:latest`
* add `--user` to `pip install`  …
=> improvement(tools/scripts): pip install with user environment

csrc/mmdeploy/backend_ops/torchscript/optimizer/ir/subgraph_matcher.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/common_subgraph_elimination.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/fuse_select_assign.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.cpp, csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.cpp
=> [Improvement] suppress onnx optimizer warning

mmdeploy/backend/coreml/backend_manager.py, mmdeploy/backend/coreml/torchscript2coreml.py, mmdeploy/pytorch/functions/topk.py, tests/test_backend/test_wrapper.py
=> [Fix] fix coreml for branch 1.x

mmdeploy/codebase/mmpose/deploy/pose_detection.py, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
fix https://github.com/open-mmlab/mmdeploy/issues/1677
=> [Fix] fix mmpose regression codec sdk export

docs/en/01-how-to-build/cmake_option.md, docs/zh_cn/01-how-to-build/cmake_option.md, mmdeploy/apis/visualize.py, mmdeploy/backend/ascend/backend_manager.py, mmdeploy/backend/ascend/wrapper.py, mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py, mmdeploy/codebase/mmdet/deploy/utils.py, mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
=> [Fix] fix ascend

csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/allClassNMS.cu
Add bounds to avoid large resource usage.
1. Pre-commit or other linting tools are used to fix the …
=> [Fix]fix trt nms jetson

csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/allClassNMS.cu
1.x of
https://github.com/open-mmlab/mmdeploy/pull/1686 …
=> [Fix]fix nms trt jetson 1.x

mmdeploy/backend/torchscript/wrapper.py
=> [Fix] import torchvision in wrapper

tools/regression_test.py
Directly set pytorch metric when it's empty for regression_test.py.
=> [Fix] Fix dbnet regression test

mmdeploy/backend/tensorrt/torch_allocator.py
Reproduce codes in master branch:
```python
from mmdeploy.backend.tensorrt.wrapper import TRTWrapper
trt_model = TRTWrapper(
'/path_to/cls/resnet/end2end.engine',
['output'])
input = torch.rand(1, 3, 224, 224).cuda()
output_trt = trt_model.forward({'input': input})
print(output_trt)
```
Error might triggered:
```
/mmdeploy/utils/logging.py(28): get_logger
Exception caught in deallocate(): TypeError: 'NoneType' object is not callable
```
or
```
codes/mmdeploy/mmdeploy/backend/tensorrt/torch_allocator.py(61): deallocate
[ERROR] Exception caught in deallocate(): AttributeError: 'NoneType' object has no attribute 'caching_allocator_delete'
```
=> [Fix] fix torch allocator resouce releasing

.github/workflows/stale.yml
Stale workflow should have `write` permission to do job such close issues per [here](https://github.com/actions/stale#recommended-permissions).
Reset to default permission, which changed in PR https://github.com/open-mmlab/mmdeploy/pull/1548
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the …
=> fix stale workflow

demo/csrc/cpp/pose_tracker.cxx, demo/csrc/cpp/utils/mediaio.h
=> [Fix] Add an option to flip webcam inputs for pose tracker demo 

csrc/mmdeploy/net/net_module.cpp
Refactor `NetModule` to support batch inference with shape clustering and split large batch (larger than model's max batch size) automatically.
=> [Refactor] Support batch inference with shape clustering

csrc/mmdeploy/apis/cxx/mmdeploy/text_recognizer.hpp, csrc/mmdeploy/codebase/mmocr/warp.cpp, csrc/mmdeploy/utils/opencv/opencv_utils.cpp, demo/csrc/cpp/utils/visualize.h
=> [Fix] Fix `WarpBbox` and memory leak in `TextRecognizer`

cmake/cuda.cmake, cmake/tensorrt.cmake
On windows, to support cmake use cuda as a language, one need to install cuda msbuild extensions that cuda installer provides.
When configure mmdeploy with cuda, if not specify cuda toolkit, cmake will use the highest cuda extensions found in `$(VCTargetsPath)\BuildCustomizations`. And it also need environment variable `CUDA_PATH_V{X}_{Y}` to be set.
When using `find_package(CUDA)`, it will first search `CUDA_PATH` and then the dir of `nvcc.exe` if `nvcc.exe` can be found. The search path should be compatible with used extensions.
- If no cuda msbuild extensions installed to vs folder
```bash
cmake  -A x64 -T v142,cuda="/path/to/cuda" ..
```
- If multiple cuda msbuild extensions installed to vs folder
```bash
cmake  -A x64 -T v142,cuda="/path/to/cuda" ..
OR
cmake -A x64 -T v142,cuda=x.y …
```
=> [Enhancement] Support cmake configure when system exists multiple cuda versions.

mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_head.py
Even though convert to tensorrt with dynamic shape successfully,
```
minshape:[1,3, 320, 320]
optshape: [8, 3, 320, 320]
maxshape: [16, 3, 320, 320]
```
The input shape somehow is always [1, 3, 320, 320] when using `trtexec` to test batch inference speed with option `--shapes`
If so, please describe how it breaks the compatibility and how the downstream …
=> [Fix] remove score filtering in rtmdet_head rewriter since it leads to error shape in batch inference

requirements/runtime.txt
- onnx<1.13.0 has high security issue (https://github.com/advisories/GHSA-ffxj-547x-5j7c)
- Python packages depending on mmdeploy cannot upgrade onnx as
- onnx==1.13.0 depends on protobuf>=3.20.2
- mmdeploy depends on protobuf<=3.20.1
- Suggesting [protobuf<=3.20.2] for quick solution
=> [Enhancement] Loosen protobuf version criteria for onnx upgrade

CMakeLists.txt, csrc/mmdeploy/apis/csharp/README.md, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_python/version.py
=> bump version to 1.0.0rc2

mmdeploy/backend/onnxruntime/wrapper.py
With the TensorRT execution provider, the ONNX Runtime delivers better inferencing performance on the same hardware compared to generic GPU acceleration. The TensorRT execution provider in the ONNX Runtime makes use of NVIDIA’s [TensorRT](https://developer.nvidia.com/tensorrt) Deep Learning inferencing engine to accelerate ONNX model in their family of GPUs. 
https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html
Does the modification …
=> [Enhance] support TensorRT engine for onnxruntime

mmdeploy/backend/tensorrt/utils.py
TensorRT's logger behaves differently from mmdeploy's logger.
``` shell
>>> import tensorrt as trt
>>> log_level = trt.Logger.ERROR
>>> logger = trt.Logger(log_level)
>>> logger.warning('This is a warning')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'tensorrt.tensorrt.Logger' object has no attribute 'warning'
>>> logger.log(log_level, 'This is a warning')
[02/14/2023-11:26:54] [TRT] [E] This is a warning
```
We should use `logger.log` method for printing infomation.
Maybe this pr can also applies to the dev branch?
=> Fix trtlogger instead of mm logger

csrc/mmdeploy/preprocess/transform/normalize.cpp
fix problem on mmdeploy sdk   normalization operation option `to_rgb` not working while `to_float` option set to false.
`csrc/mmdeploy/preprocess/transform/normalize.cpp` …
=> [FIX] sdk normalization to_rgb option not working

csrc/mmdeploy/apis/c/mmdeploy/classifier.cpp, csrc/mmdeploy/apis/c/mmdeploy/detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/pipeline.cpp, csrc/mmdeploy/apis/c/mmdeploy/pipeline.h, csrc/mmdeploy/apis/c/mmdeploy/pose_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp, csrc/mmdeploy/apis/c/mmdeploy/rotated_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp, csrc/mmdeploy/apis/c/mmdeploy/text_detector.cpp, csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.cpp, csrc/mmdeploy/apis/c/mmdeploy/video_recognizer.cpp, csrc/mmdeploy/core/model.cpp, csrc/mmdeploy/core/model.h, csrc/mmdeploy/core/model_impl.h, csrc/mmdeploy/graph/inference.cpp, csrc/mmdeploy/model/CMakeLists.txt, csrc/mmdeploy/model/directory_model_impl.cpp, csrc/mmdeploy/model/zip_model_impl.cpp
=> [Improvement] Add `Model::ReadConfig` & simplify handle creation

csrc/mmdeploy/preprocess/transform/normalize.cpp
fix problem on mmdeploy sdk normalization operation option to_rgb not working while to_float option set to false.
`csrc/mmdeploy/preprocess/transform/normalize.cpp` …
=> [FIX] sdk normalization to_rgb option not working(dev1.x)

csrc/mmdeploy/codebase/mmdet/yolo_head.cpp, csrc/mmdeploy/codebase/mmdet/yolo_head.h
MMYOLO used YOLOv5Head instead of YOLOV5Head.
Change YOLOV5Head to YOLOv5Head.
=> [fix] Fix component not found issue by changing `class YOLOV5Head` to ` class YOLOv5Head`

MANIFEST.in, tools/package_tools/mmdeploy_builder.py
- `mmdeploy_onnx2ncnn` executable shoud be copied to  wheel.
- bdist wheel seems copy `build/lib/*` to wheel which should be prevented.
https://github.com/pypa/wheel/issues/147
=> [Fix] Fix package_tools

csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
RTMPose FP16 model will be nan on Android platform using ncnn. So force set ncnn Reduction op for FP32.
Add `31=15` to Reduction layer params automatically when executing onnx2ncnn.
None.
None.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions …
=> [Fix] Fix reduction fp16 exceed

docs/en/get_started.md, requirements/runtime.txt
#1720 
"
In addition, there is a [high security issue for onnx<1.13.0](https://github.com/advisories/GHSA-ffxj-547x-5j7c) but onnx==1.13.0 has dependency conflict w/ mmdeploy==0.12.0. I hope this issue also could be resolved soon.
"
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
=> [Enhancement] upgrade onnx to 1.13.0 to resolve security issue

mmdeploy/apis/utils/utils.py, mmdeploy/codebase/mmrazor/deploy/__init__.py, mmdeploy/codebase/mmrazor/deploy/mmrazor.py, mmdeploy/utils/config_utils.py, mmdeploy/utils/constants.py
We add a new Codebase to support mmrazor. Besides, we modify build_task_processor to detect mmrazor config.
=> support mmrazor

csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.cpp, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.hpp, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cu, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cuh, csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.hpp, docs/en/06-custom-ops/tensorrt.md, mmdeploy/backend/tensorrt/wrapper.py, mmdeploy/mmcv/ops/__init__.py, mmdeploy/mmcv/ops/multi_scale_deform_attn.py, tests/test_ops/test_ops.py
This trt plugin refers to [mmcv](https://github.com/open-mmlab/mmcv/blob/2.x/mmcv/ops/csrc/common/cuda/points_in_boxes_cuda_kernel.cuh) and [tensorrt](https://github.com/NVIDIA/TensorRT/blob/main/plugin/multiscaleDeformableAttnPlugin/README.md)
If so, please describe how it breaks the compatibility and how the downstream projects should modify their …
=> support multi_scale_deform_attn trt plugin

CMakeLists.txt, cmake/MMDeploy.cmake, csrc/mmdeploy/apis/c/CMakeLists.txt, csrc/mmdeploy/apis/cxx/CMakeLists.txt, demo/csrc/CMakeLists.txt
=> [Fix] Export `mmdeploy` only in monolithic build

csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp, demo/python/object_detection.py, mmdeploy/codebase/mmdet/deploy/object_detection.py
=> [Enhancement] Support RTMDet-Ins

mmdeploy/codebase/mmcls/models/classifiers/base.py, tests/regression/mmcls.yml
=> mmclassification ConformerHead support

csrc/mmdeploy/apis/python/pose_tracker.cpp
There is a bug in Python binding of PoseTracker. When inference result has no human body, there is possibility that a `ValueError: negative dimensions are not allowed numpy` exception raised. I made some digging and found that:
1. when no human found in the image, an empty `Result` object is created but `keypoint_count` is uninitialized;
2. when creating `py::array_t` in Python version `Apply` function, `keypoint_count` is used to initialize the array shape;
3. in this case, `keypoint_count` is random value, when it is negative, the `py::array_t` would fail to create.
Add a check before reading `keypoint_count`.
No.
No.
4. The modification is covered by complete unit tests. If not, please add more unit tests …
=> fix pose_tracker python api will raise ValueError when result has no human

configs/mmrotate/rotated-detection_onnxruntime_static.py, mmdeploy/codebase/mmrotate/deploy/rotated_detection.py, tests/regression/mmpose.yml, tools/regression_test.py
=> [Fix]: Fix mmrotate and regression script

docker/prebuild/Dockerfile, tools/scripts/build_prebuild_image.sh
=> [Enhancement]: update toolset of prebuild image

docs/en/04-supported-codebases/mmocr.md, docs/zh_cn/04-supported-codebases/mmocr.md, mmdeploy/codebase/mmocr/models/text_recognition/sar_decoder.py, mmdeploy/codebase/mmocr/models/text_recognition/sar_encoder.py, tests/regression/mmocr.yml
Fixed SAR exporting for TorchScript. Updated the status of SAR.
=> [Doc] update SAR status

docs/en/04-supported-codebases/mmcls.md, docs/zh_cn/04-supported-codebases/mmcls.md
=> [Docs] Update mmcls doc

csrc/mmdeploy/net/openvino/openvino_net.cpp, docker/CPU/Dockerfile
The openvino-dev version of based image is different with pip installed one, therefore the converted openvino model can't be loaded by sdk.
Previously, the openvino model will first rewrite to /tmp directory and load, which is not right when loading two openvino models at the same time. And this strategy has more overhead.
=> [Enhancement] Load openvino model from memory

mmdeploy/codebase/mmpose/deploy/pose_detection.py, tools/onnx2ncnn_quant_table.py
fix https://github.com/open-mmlab/mmdeploy/issues/1991
dataloader for ppq
=> [Fix] Fix dataloader for ncnn quantization

requirements/readthedocs.txt
fix readthedocs urllib:  https://github.com/open-mmlab/mmengine/pull/1132
3. If the modification has a dependency on downstream projects of a newer version, this PR should …
=> [Fix]: limit urllib3 for readthedocs

csrc/mmdeploy/preprocess/transform/pad.cpp, csrc/mmdeploy/preprocess/transform/resize.cpp, tests/test_csrc/preprocess/test_pad.cpp, tests/test_csrc/preprocess/test_resize.cpp
https://mmcv.readthedocs.io/en/2.x/understand_mmcv/data_transform.html
=> [Fix] swap width and height in Resize and Pad according to upstream codebases

csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3.cpp, csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3.hpp, csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3_kernel.cu, csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3_kernel.hpp, docs/en/06-custom-ops/tensorrt.md, docs/zh_cn/06-custom-ops/tensorrt.md
I did not add a unit test since no PyTorch implementation is available in MMCV.
=> add deform conv v3 plugin

.github/workflows/publish.yml
uploading assets fails due to the wrong tag_name of action `softprops/action-gh-release@v1`. See issue https://github.com/softprops/action-gh-release/issues/360
use gh script to upload assets
3. If the modification has a dependency on …
=> fix uploading assets

mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet/models/dense_heads/yolox_head.py, tests/test_apis/test_onnx2openvino.py
fix https://github.com/open-mmlab/mmdeploy/issues/2144  https://github.com/open-mmlab/mmdeploy/issues/2133
1. remove `mmdet.` domain in mmyolo pipelines
2. remove redundant score filtering before nms for yolox
4. If the modification …
=> fix export info for mmyolo

mmdeploy/codebase/mmocr/models/text_recognition/__init__.py, mmdeploy/codebase/mmocr/models/text_recognition/nrtr_decoder.py, mmdeploy/codebase/mmocr/models/text_recognition/satrn_encoder.py, tests/test_codebase/test_mmocr/test_mmocr_models.py
The for-loops are not exported to onnx model.
https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/decoders/nrtr_decoder.py#L134-L138
https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/encoders/satrn_encoder.py#L84-L86
=> [Fix] fix satrn onnxruntime batch inference

configs/mmdet3d/voxel-detection/voxel-detection_static.py, mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py, mmdeploy/codebase/mmdet3d/models/mvx_two_stage.py
=> Fix torch2onnx for pointpillars with multi-level outputs

mmdeploy/codebase/mmpose/models/heads/yolox_pose_head.py, tools/regression_test.py
fix regression test with maskrcnn
fix yolox-pose keep_tok_k
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with …
=> fix reg test for maskrcnn

mmdeploy/codebase/mmpose/models/heads/yolox_pose_head.py, tests/test_codebase/test_mmpose/test_mmpose_models.py
=> update yolox-pose ut

csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp, mmdeploy/codebase/mmdet/deploy/object_detection.py
Add is_resize_mask configuration option in instance segmentation.
Support output cropped mask or mask consistent with input image shape.
=> add is_resize_mask cfg in inst seg

mmdeploy/__init__.py
=> fix mmdeploy.version_info

csrc/mmdeploy/net/rknn/rknn_net.cpp, docs/en/01-how-to-build/rockchip.md, docs/zh_cn/01-how-to-build/rockchip.md, mmdeploy/backend/rknn/onnx2rknn.py
=> update rknn-toolkit2 version to 1.5

.github/workflows/regression-test.yml, configs/_base_/backends/onnxruntime-fp16.py, configs/mmaction/video-recognition/video-recognition_onnxruntime-fp16_static.py, configs/mmagic/super-resolution/super-resolution_onnxruntime-fp16_dynamic.py, configs/mmdet/detection/detection_onnxruntime-fp16_dynamic.py, configs/mmdet/instance-seg/instance-seg_onnxruntime-fp16_dynamic.py, configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime-fp16_dynamic.py, configs/mmocr/text-detection/text-detection_onnxruntime-fp16_dynamic.py, configs/mmocr/text-recognition/text-recognition_onnxruntime-fp16_dynamic.py, configs/mmpose/pose-detection_onnxruntime-fp16_static.py, configs/mmpose/pose-detection_simcc_onnxruntime-fp16_dynamic.py, configs/mmpretrain/classification_onnxruntime-fp16_dynamic.py, configs/mmrotate/rotated-detection_onnxruntime-fp16_dynamic.py, configs/mmseg/segmentation_onnxruntime-fp16_dynamic.py, docs/en/05-supported-backends/onnxruntime.md, docs/en/05-supported-backends/openvino.md, docs/zh_cn/05-supported-backends/onnxruntime.md, docs/zh_cn/05-supported-backends/openvino.md, mmdeploy/backend/onnxruntime/backend_manager.py, mmdeploy/backend/onnxruntime/wrapper.py, tests/regression/mmaction.yml, tests/regression/mmagic.yml, tests/regression/mmdet.yml, tests/regression/mmdet3d.yml, tests/regression/mmocr.yml, tests/regression/mmpose.yml, tests/regression/mmpretrain.yml, tests/regression/mmrotate.yml, tests/regression/mmseg.yml
Support onnxruntime-fp16 by using the float16 conversion tool [onnxconverter-common](https://onnxruntime.ai/docs/performance/model-optimizations/float16.html#float16-conversion)
1. Modify onnxruntime `to_backend` and `ORTWrapper` to support float16 conversion and inference.
2. Update onnxruntime document.
3. Add `onnxruntime-fp16` deploy configs for all codebases.
4. Add ort-fp16 test pipeline in regression configs
1. Pre-commit …
=> Support onnxruntime fp16

mmdeploy/mmcv/ops/nms_rotated.py
This PR addresses a runtime error that occurs when exporting ONNX with dummy data (i.e., when no objects are present). Specifically, the issue arises from the `ONNXNMSRotatedOp` class in the `nms_rotated.py` file.
The problem was that when no objects were detected (resulting in `indices` being empty), a `RuntimeError` occurred when `torch.cat(indices)` was called. To resolve this issue, I added a condition to check the length of `indices` before concatenating. If `indices` is empty, it now returns a tensor of zeros with …
=> [Fix] Prevent RuntimeError in ONNX export with empty input in ONNXNMSRotatedOp

mmdeploy/pytorch/functions/__init__.py, mmdeploy/pytorch/functions/copy.py, tests/test_pytorch/test_pytorch_functions.py
=> fix pytorch deepcopy trace error

demo/csrc/cpp/classifier.cxx, demo/csrc/cpp/detector.cxx, demo/csrc/cpp/pose_detector.cxx, demo/csrc/cpp/restorer.cxx, demo/csrc/cpp/rotated_detector.cxx, demo/csrc/cpp/segmentor.cxx
deploee needs model inference time cost 
add time profiler
=> feat(demo): add time profile

demo/csrc/cpp/utils/palette.h
The output for cv::kmeans is CV_32FC1, if doesn't reshpae c_mat, it will allocate new memory and the centers will all be zero.
=> [Fix] Fix random color for Palette

.github/scripts/test_onnx2ncnn.py, .github/workflows/backend-ncnn.yml, .github/workflows/backend-snpe.yml, .github/workflows/build.yml, .github/workflows/regression-test.yml, .github/workflows/stale.yml, .readthedocs.yml, mmdeploy/apis/onnx/export.py, mmdeploy/codebase/mmdet/deploy/object_detection_model.py, tests/test_apis/test_onnx_passes.py
=> fix urls in CI and readthedocs

docs/en/03-benchmark/supported_models.md, docs/en/04-supported-codebases/mmpretrain.md, docs/zh_cn/03-benchmark/supported_models.md, docs/zh_cn/04-supported-codebases/mmpretrain.md, mmdeploy/codebase/mmpretrain/deploy/classification.py, tests/regression/mmpretrain.yml
Support conversion of mmpretrain's Mobilenet V3 classification models to ONNX.
Fixes error that was arising during conversion to ONNX: https://github.com/open-mmlab/mmdeploy/issues/2245
=> Mobilenet V3 to ONNX support

csrc/mmdeploy/preprocess/transform/load.cpp
super-resolution task read images in rgb format 
https://github.com/open-mmlab/mmagic/blob/main/configs/srcnn/srcnn_x4k915_1xb16-1000k_div2k.py#L52-L66
=> fix img load for super-resolution in sdk

csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp
[bugfix] windows下编译onnxruntime自定义算子时出错"C3863不可指定数组类型" https://github.com/open-mmlab/mmdeploy/issues/2430
使用std::vector替代数组，即将`float tmp[N];`修改为`std::vector<float> tmp(N);`
=> fix ONNXRuntime Compiler Error

mmdeploy/mmcv/ops/roi_align.py
The `RoiAlign` op parameters are different with [ONNX document](https://github.com/onnx/onnx/blob/main/docs/Operators.md#roialign) when opset>=16 in `roi_align_default` function, and the `Squeeze` op in this symbolic function is also wrong when the opset>=13. This PR fixed them.
Add judgment of opset version for `Squeeze` op, and change the `RoiAlign` op parameters when opset>=16.
If so, please describe how it …
=> fix roi align symbolic function in onnx opset>=16

.github/md-link-config.json, .github/workflows/regression-test.yml, configs/mmdet/detection/single-stage_ncnn_static-640x640.py, docs/en/04-supported-codebases/mmdet3d.md, docs/zh_cn/04-supported-codebases/mmdet3d.md, mmdeploy/codebase/mmdet/deploy/object_detection.py, mmdeploy/codebase/mmdet3d/deploy/mono_detection.py, mmdeploy/codebase/mmdet3d/models/base.py, mmdeploy/codebase/mmdet3d/models/mvx_two_stage.py, mmdeploy/codebase/mmdet3d/models/single_stage_mono3d.py, tests/regression/mmdet.yml, tests/test_codebase/test_mmdet3d/test_mmdet3d_models.py
=> fix torch2onnx for mmdet3d

mmdeploy/mmcv/ops/nms.py, mmdeploy/pytorch/functions/multi_head_attention_forward.py
=> Fix conversion with rtmdet-inst, vit, conformer

CMakeLists.txt, csrc/mmdeploy/apis/csharp/README.md, demo/csharp/image_classification/image_classification.csproj, demo/csharp/image_restorer/image_restorer.csproj, demo/csharp/image_segmentation/image_segmentation.csproj, demo/csharp/object_detection/object_detection.csproj, demo/csharp/ocr_detection/ocr_detection.csproj, demo/csharp/ocr_recognition/ocr_recognition.csproj, demo/csharp/pose_detection/pose_detection.csproj, docs/en/02-how-to-run/prebuilt_package_windows.md, docs/en/get_started.md, docs/zh_cn/02-how-to-run/prebuilt_package_windows.md, docs/zh_cn/get_started.md, mmdeploy/version.py, tools/package_tools/packaging/mmdeploy_runtime/version.py
Bump version v1.3.0
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream …
=> Bump version v1.3.0

.github/workflows/docker.yml, .github/workflows/publish.yml, configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py, csrc/mmdeploy/codebase/mmpose/simcc_label.cpp, mmdeploy/codebase/mmpose/codecs/__init__.py, mmdeploy/codebase/mmpose/codecs/post_processing.py, mmdeploy/codebase/mmpose/deploy/pose_detection.py, mmdeploy/codebase/mmpose/deploy/pose_detection_model.py, mmdeploy/codebase/mmpose/models/heads/__init__.py, mmdeploy/codebase/mmpose/models/heads/simcc_head.py
export get_simcc_maximum for simcc and rtmpose models.
Support torch2onnx with post-processing `get_simcc_maximum` for `onnxruntime` and `tensorrt` backend.
- Note that `ncnn` backend is not supported in this PR.
None
```
codebase_config = dict(
export_postprocess=True  # export get_simcc_maximum
)
```
4. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
5. The documentation has been modified accordingly, like docstring or example tutorials.
=> export get_simcc_maximum for simcc

docs/en/01-how-to-build/windows.md, docs/zh_cn/01-how-to-build/windows.md
… platform
Suport more backend on windows
Update the document of building mmdeploy with ncnn backend on Windows platform
None
None …
=> CodeCamp2023-670

docs/en/04-supported-codebases/mmdet.md, docs/zh_cn/04-supported-codebases/mmdet.md, mmdeploy/codebase/mmdet/models/roi_heads/__init__.py, mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py, mmdeploy/codebase/mmdet/models/roi_heads/htc_roi_head.py, tests/regression/mmdet.yml
address https://github.com/open-mmlab/mmdeploy/issues/2409
=> support htc

csrc/mmdeploy/apis/c/mmdeploy/common.cpp
fix #2523 #2525 
use different cuda stream when create handle.
=> use different stream when create handle

mmdeploy/codebase/mmdet/deploy/object_detection.py, setup.py
I use mmdeploy in my project.
Added the ability to build a project with PyTorch 2.0.
Namely, I added the flag -std=c++17 to extra_compile_args in setup.py depending on the version of Torch like mmcv setup.py.
https://github.com/open-mmlab/mmcv/blob/main/setup.py#L203
=> Added the ability to build a project with PyTorch 2.0.

mmdeploy/codebase/mmdet/deploy/object_detection.py
I use mmdeploy in my project.
There was an error when using a model from the mmyolo repository during image preprocessing, provided that an np.ndarray was supplied as input. If you input the path to the image, everything works fine.
Error reproduction code:
```python
from mmdeploy.apis.utils import build_task_processor
from mmdeploy.utils import get_input_shape, load_config
import torch
import cv2
deploy_cfg = './configs/deploy/detection_tensorrt_dynamic-192x192-960x960.py'
model_cfg = '../mmyolo/configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py'
device = 'cuda:0'
backend_model = ['./work_dir/end2end.engine']
image_str = '../mmyolo/demo/demo.jpg'
image_np = cv2.imread(image_str)
deploy_cfg, model_cfg = load_config(deploy_cfg, model_cfg)
task_processor = build_task_processor(model_cfg, …
```
=> Add prefix mmdet to LoadImageFromNDArray

mmdeploy/utils/config_utils.py
The value needs to be converted to string first.
When trying to 
```python
from mmdeploy.utils import get_input_shape, load_config
deploy_cfg = 'configs/mmpretrain/classification_onnxruntime_dynamic.py'
model_cfg = 'mmpretrain/configs/resnet/resnet18_8xb32_in1k.py'
deploy_cfg, model_cfg = load_config(deploy_cfg, model_cfg)
```
the `load_config` throws an error because
```python
if model_cfg.get('_scope_', None) == 'mmrazor'\
or model_cfg['type'].startswith('mmrazor.'):
```
the '`type` value is not string for the function …
=> Fix "has no attribute startswith"

mmdeploy/codebase/base/task.py
Some models don't have any default scope, which means
```
if not DefaultScope.check_instance_created(self.experiment_name):
self.scope = DefaultScope.get_instance(
self.experiment_name,
scope_name=self.model_cfg.get('default_scope'))
)
```
returns `None` which causes an error because `scope_name` should be string.
Convert to string while retrieving value for `scope_name`
=> Fix error when default_scope is None

mmdeploy/codebase/mmpose/deploy/pose_detection.py
This fixes a missing `img_path` variable error when a list of arrays are passed to `create_input()` for pose detection.
Initialize empty list of `img_path`s for array input.
=> Fix pose inference on list of ndarrays

csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp, mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Fix wrong size of mask in rtmdet-ins post-processing. #2580 https://github.com/open-mmlab/mmdetection/issues/11230
reverse the width and height in `scale_factor`
3. If the …
=> Fix wrong size of mask in RTMDet-Ins post-processing

mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py
Fixes #2787
This _pull request_ addresses an issue encountered when exporting single-stage detectors (e.g., **RetinaNet** and detectors inheriting `SingleStageDetector`) from **MMDetection** using **MMDeploy** to **ONNX** format. The problem stems from improper handling of _softmax_ scores, resulting in an `IndexError` during export.
The root cause of the issue was the repeated slicing (`[:, :, :-1]`) of the scores tensor—first on `scores` and then again during the parsing of `max_scores` from `nms_pre_score`. This inadvertently excluded the _last class index_ for single-stage detectors, causing an `IndexError` during the `torch.max` operation for single-class models because the scores tensor became empty. In a multi-class setting, this also excluded the last-index class from the softmax …
=> [Fix]: Resolve Error Exporting RetinaNet for Single Class Case with CrossEntropyLoss in MMDeploy
